### ISSUE TITLE
no complete code is shown

### ISSUE THREAD

**Issue by Psychopixel** [stackblitz/bolt.new#1980] opened 2024-11-11 10:27 UTC
### Describe the bug

many times the code shown is not complete 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-jkzvco

### Steps to reproduce

ask some modification to code, sometimes the new code shown in the code window is not complete

### Expected behavior

all the code should be shown

### Platform

```
Browser name = Chrome
Full version = 130.0.0.0
Major version = 130
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 71788896,
  "usedJSHeapSize": 67096740,
  "jsHeapSizeLimit": 4294705152
}
Username = Psychopixel
Chat ID = 427073e56d45
```

**Comment by endocytosis** [comment] 2024-11-13 17:12
Appreciate the feedback! At times there are programming challenges that are too complex for the AI to solve. Sometimes pasting any error messages from the terminal into the chat is successful in resolving issues. At other times, manual intervention is required to prevent excessive token usage, which may include writing additional code. This page [here](https://github.com/stackblitz/bolt.new/issues/678) has a number of helpful insights on using Bolt effectively while maximizing token efficiency. Appreciate your patience as the team continues to make improvements!

**Closed by endocytosis** 2024-11-13 17:12 UTC

**Comment by chrislaupama** [comment] 2024-11-21 02:52
Wanting to confirm here.

While the code is fully generated ( you can see it generate to completion ) and the preview correctly displays the code as intended the actual code in the code IDE panel is cut off so you don't get to see the fully displayed code.

It's certainly there, just gets cut off for some reason.
