### ISSUE TITLE
Getting rate limit after using it for 15 minutes and paid for the PRO plan

### ISSUE THREAD

**Issue by reech1** [stackblitz/bolt.new#270] opened 2024-10-09 07:29 UTC
### Describe the bug

getting the follwing message: You have hit the rate limit. You can continue to code for free in the editor.

theres no way I hit the limit in 15 minutes of use. Please help

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-46amgb

### Steps to reproduce

just type any instruction and you will get the message

### Expected behavior

unable to continue editing the project with AI (Boolt)

### Platform

- OS: macOS, 
- Browser:  Chrome, 
- Version: [e.g. 91.1]

**Comment by danvilenica** [comment] 2024-10-09 07:31
I have the same issue, not that fast but 2 hours maybe.

**Comment by Athreyas** [comment] 2024-10-09 07:34
I have the similar issue too. I have been using it earlier today. But for the project it has rate limit error even with premium account. 

<img width="473" alt="image" src="https://github.com/user-attachments/assets/9044b068-1c2d-4ff3-9cd9-30af869e2b26">

**Comment by faridbouchdak** [comment] 2024-10-09 07:35
Same issue here. paid and got rate limited directly.

**Comment by reech1** [comment] 2024-10-09 07:39
Is customer support replying these complaints ?? any of you talked with stackblitz support about this?

**Comment by Abraham12611** [comment] 2024-10-09 07:41
I can find any contact info on their website.

**Comment by reech1** [comment] 2024-10-09 07:46
this MUST be a bug, same complaints keep coming in over and opver from multiple users in the "ISSUES" thread ... crazy

**Comment by aiiven** [comment] 2024-10-09 07:47
Same problem here. I used it for a day only and now it's already hitting limit. I'm pretty sure I did not consume 10M tokens...

**Comment by GoThundercats** [comment] 2024-10-09 08:17
15 mins wow, this shows there is a significant problem at HeadQuarters. There have been complaints that maybe the code is re-writing the whole project even after small iterations, which may explain why it's using so many tokens.

**Comment by reech1** [comment] 2024-10-09 08:20
> 15 mins wow, this shows there is a significant problem at HeadQuarters. There have been complaints that maybe the code is re-writing the whole project even after small iterations, which may explain why it's using so many tokens.

Yes probably rewriting the entire code or page for every AI command..  hope they fix this issue quick everyone is having the same issue looks like...

**Comment by sulco** [comment] 2024-10-09 10:32
Hey everyone, thank you for reporting the issue! We are actively working on a solution and implementing several changes to support token reloading and provide a clearer in-app status for the tokens. We appreciate your patience and will deploy the first updates as soon as possible so today and over the next couple of days, you can expect a continually improving experience.

**Comment by sulco** [comment] 2024-10-09 11:24
Hey, @reech1! While we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. _So yes, this was a bug._

We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you all for being our early adopters and for your patience as we're improving the bolt experience!

**Closed by sulco** 2024-10-09 11:24 UTC

**Comment by The-Techy-Boy** [comment] 2024-11-30 18:29
![image](https://github.com/user-attachments/assets/1c88eef4-99ac-4293-8541-d2de3fc7bc8e)
 I am gettin the same issue , when this issue , how much time it takes , to comebacks to its original rate limit

**Comment by DontTemptFate** [comment] 2024-12-01 13:57
![image](https://github.com/user-attachments/assets/7f4528ed-63ae-450a-a7ad-cc425be3557c)
Ive using not even 20 minutes, is something going on again?

**Comment by spaceman6** [comment] 2024-12-03 21:06
Stopped working 7:45pm yesterday. Did absolutely nothing today. 
Hit the rate limit just after opening my project at 4pm. 
Not on paid plan though.

**Comment by wizardbeard** [comment] 2024-12-24 04:43
I started a free account with the intent to upgrade, but after ~10 minutes, I hit a rate limit.

**Comment by DavidOsipov** [comment] 2024-12-30 19:20
Same issue here, don't want to upgrade - I haven't even tried it properly

**Comment by berkim20** [comment] 2025-01-04 16:56
Same issue. What's the problem? Where is the informations about the limits located?

**Comment by mahmoudkhalifah** [comment] 2025-01-06 22:17
same issue, I am on free plan and I have a lot of tokens.
![image](https://github.com/user-attachments/assets/20d8eeeb-88a6-4bca-b3c2-ef860a41ebb5)

**Comment by jrespie** [comment] 2025-01-09 23:31
Same issue, 839 tokens remaining.

I guess there is some another rate limit being applied. Maybe calls per day? On a free plan, lovable.dev only allows 5 calls per day, I guess bolt has something similar.

**Comment by ilike-white** [comment] 2025-01-09 23:44
> Maybe calls per day?
I think so. It might be ratelimited in terms of calls per day. I don't think it would be rate limited based purely on tokens since I (along with others) have over 500k tokens, which should at the minimum allow us to have 5+ more messages.

**Comment by jrespie** [comment] 2025-01-10 02:13
> > Maybe calls per day?
> 
> ~I think so. It might be ratelimited in terms of calls per day. I don't think it would be rate limited based purely on tokens since I (along with others) have over 500k tokens, which should at the minimum allow us to have 5+ more messages.~
> 
> I just found the reason free plans are getting rate limited is because there is a **150,000 daily token limit for free plans** and a **1,000,000 monthly token limit**. Check how much you have used so far in _Settings>Tokens_.
> 
> I'm unsure about the paid plans; however, I would assume the same token limit is applied, but a higher limit.
> 
> **CREDIT TO: [#5098 (comment)](https://github.com/stackblitz/bolt.new/issues/5098#issuecomment-2575454263)**

Ah great detective work, thanks @ilike-white

**Comment by SandeshBro-ux** [comment] 2025-01-24 02:46
I think you guys should increase the timing to 30 mins.

**Comment by dazistgut** [comment] 2025-01-26 20:36
I find it quite deceptive that the approach is to hide the daily/monthly limits from the webpage, and even the upgrade/pricing page... The website suggests you have x tokens, and you pay for x tokens, but you're not actually going to be able to use them due to daily/monthly limits...

Please can you share the outline of each of the limits, of each plan @sulco @kc0tlh

**Comment by Brewlot** [comment] 2025-01-27 14:29
![Image](https://github.com/user-attachments/assets/02a65e92-6c42-4c90-acf1-01146be475ae)

I have almost 7m tokens left and I am rate limited on my first message in over a week....

This product really pisses me off more than it makes me happy... First it would waste your token sbut rewriting the entire code base with a simple change, now this rate limiting shit so people loose their purchased tokens. I am sure they wont do anything about it either even though we have subscribed and topped up and everything.

**Comment by slowtravelpace** [comment] 2025-02-02 20:54
Same for me ! just paid the pro plan today and got the message ! can you fix that please ? Thx !

**Comment by surj** [comment] 2025-02-06 01:34
Feb 3rd, I just started to evaluate this for selection. Super impressed but then stopped dead. Like an idiot I got it to teach me. Happy to upgrade to pro, butalso wondering if my $50 pcm will just be flushed away. I know you guys are hiring and scaling fast but this is the part of the go to market where you can lose your early traction fast. Figure out support fast, hire an old person that has done this before. How about crowdsourcing it with your closest fans if dunds are not forthcoming?

**Comment by Seaniiboi04** [comment] 2025-02-10 07:05
I got the Rate Limit issue too, and it is at the worst time.  I am almost done with my project and I am ready to launch but can perform my final touches.  I have the paid plan and only worked on it for an hour.  

> ![Image](https://github.com/user-attachments/assets/02a65e92-6c42-4c90-acf1-01146be475ae)
> 
> I have almost 7m tokens left and I am rate limited on my first message in over a week....
> 
> This product really pisses me off more than it makes me happy... First it would waste your token sbut rewriting the entire code base with a simple change, now this rate limiting shit so people loose their purchased tokens. I am sure they wont do anything about it either even though we have subscribed and topped up and everything.
> 
> Not to mention they don't seem to reply to any issues or complaints.

I also got the Rate Limit issue, and it is at the worst time.  I am almost done with my project and ready to launch, but I can still do my final touches.  I have the paid plan and only worked on it for an hour.  Everything you said was spot on and reflects my experience as well.  Bolt is very confusing and frustrating. It eats away at your tokens and doesn't provide results more than half the time.  It rewrites the entire code instead of changing the part that needs fixing.  Sometimes, the code they create is not efficient, and that is why it keeps breaking.  I saw that part of my code was 2000 lines, and when I went in, I got it down to 200, and it worked just fine.

and yep, no replies to anything.

**Comment by AditiKhedkar** [comment] 2025-02-10 17:51
why is this issue closed? same issue occuring despite getting pro

**Comment by surj** [comment] 2025-02-10 23:22
@AditiKhedkar It's easier to claim that it is working and fixed then ignore it rather than to try and be professional and hire support people. If it is paid for they should provide some professionally credible and functional support.

**Comment by slarrain** [comment] 2025-02-28 18:13
Thanks for people reporting on this. I just hit the daily limit and was thinking of getting pro to finish the project, but given that pro users have also hit the limit, then I will not go that route.

**Comment by DavidOsipov** [comment] 2025-02-28 18:58
why the issue is closed? Who closed the issue? 

Oh, you know what, I'm ceasing using the account.

**Comment by VeraciousEquivocation** [comment] 2025-03-02 20:49
you can burn the daily limit in a single prompt on free, and on pro tier. 
At that rate, it's not worth it unless you throw money at them. Their target audience is clearly big business.

This is not an issue or bug in their eyes. It's a deceptive feature.

**Comment by tallals** [comment] 2025-03-14 23:37
for a pro plan I get

You have hit the rate limit. You can continue to code for free in the editor.

**Comment by MichaelShawJ** [comment] 2025-03-19 18:56
So Glad I didn't pay yet. I was able to type for 5 minutes and I'm cut off? hahaha Okay nice. I thought I would at least get the free trial for 2 weeks of something usable. But if this is the trial, then consider it judged. Even the basic react/expo website gives you a fully functional two-page app with nav bar for free hahaha

**Comment by Gabgabu** [comment] 2025-03-29 21:22
before paying I was googling on the Bolt limit and this was the 1st topic came up. 
I'm definitly moving to Base44 as I get a free 15 prompts\day before paying
Pro will surely work there too

**Comment by cTes** [comment] 2025-03-30 20:52
![Image](https://github.com/user-attachments/assets/375e37f8-9986-4ed6-9b1b-d4c33d848081)
Same issue here, don't want to upgrade - I haven't even tried it properly

**Comment by elvin2000x** [comment] 2025-04-03 05:06
I did probably a million dollars worth of coding in 7 hours and hit the rate limit. Sads.

**Comment by elvin2000x** [comment] 2025-04-03 05:07
Best first day ever!

**Comment by gabrielrozeno** [comment] 2025-04-05 21:52
Thank God I saw this before paying for Pro. There is no chance I will upgrade after seeing that it is useless.

**Comment by ShakthiNandan** [comment] 2025-04-21 18:43
This issue is likely closed because of the answer given here
There is a daily limit of 150K tokens
that explains why I'm left with exactly 850K tokens
and there is a monthly 1Mil token limit too

Hope this helps

> > Maybe calls per day?
> 
> ~I think so. It might be ratelimited in terms of calls per day. I don't think it would be rate limited based purely on tokens since I (along with others) have over 500k tokens, which should at the minimum allow us to have 5+ more messages.~
> 
> I just found the reason free plans are getting rate limited is because there is a **150,000 daily token limit for free plans** and a **1,000,000 monthly token limit**. Check how much you have used so far in _Settings>Tokens_.
> 
> I'm unsure about the paid plans; however, I would assume the same token limit is applied, but a higher limit.
> 
> **CREDIT TO: [#5098 (comment)](https://github.com/stackblitz/bolt.new/issues/5098#issuecomment-2575454263)**

**Comment by HariEshwar-J-A** [comment] 2025-05-22 22:49
> Hey, [@reech1](https://github.com/reech1)! While we have been working on optimizing the tokens usage we have accidentally triggered the limit on the accounts that weren't close to the limit. _So yes, this was a bug._
> 
> We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you all for being our early adopters and for your patience as we're improving the bolt experience!

Please fix this!

**Comment by moyarich** [comment] 2025-06-13 23:20
on pro plan and triggered the rate limit
