### ISSUE TITLE
Netlify deployment URL reported as 'undefined'

### ISSUE THREAD

**Issue by schmidthaus** [stackblitz/bolt.new#3948] opened 2024-12-10 10:27 UTC
### Describe the bug

Netlify deployment URL reported as 'undefined' after deploying the app.

### Link to the Bolt URL that caused the error

https://bolt.new/~/stackblitz-starters-aa5ovvzr

### Steps to reproduce

1. Click Deploy.
![CleanShot 2024-12-10 at 12 25 59@2x-optimised](https://github.com/user-attachments/assets/b9ef51c8-bf4d-4e82-b030-a62e003d893f)

### Expected behavior

Deployment URL (and preferably a netlify claim url)

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 175388065,
  "usedJSHeapSize": 151174897,
  "jsHeapSizeLimit": 4294705152
}
Username = schmidthaus
Chat ID = ca3ffe5bfd1d
```

**Comment by AriPerkkio** [comment] 2024-12-10 13:16
Hey @schmidthaus, thanks for the report. I'm able to reproduce the bug.

This issue is tracked internally now.

**Comment by AriPerkkio** [comment] 2024-12-10 13:18
The root cause here is that your project's `npm run build` command fails. Bolt doesn't detect that error and tries to continue with deployment.

In your project you should check why `npm run build` is failing. Deployments should work after resolving that.

**Closed** 2024-12-18 13:16 UTC
Labels: Linear Created
