### ISSUE TITLE
Bolt.new unable to get past 'npm install && npm start' setups

### ISSUE THREAD

**Issue by magusonline** [stackblitz/bolt.new#176] opened 2024-10-07 22:27 UTC
### Describe the bug

There seems to be issues with Bolt.new setting up dependencies of any kind. They offer "fixes" which essentially loop into various recursion loops of the same problem to "fix" without actually fixing anything.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-nwbhho

### Steps to reproduce

1. Click 'fix'
2. Wait for resolution
3. Click new 'fix' 
4. Wait for resolution
5. Click new new 'fix'
6. Wait for resolution
7. Click new new new 'fix' (it's actually 3's issue repeated)
8. Wait for resolution
9. Click on new new new 'fix' (it's actually 1's issue repeated)

### Expected behavior

It should install the dependencies instead of going down an infinite loop.

### Platform

Windows 10
Firefox 131.0

**Comment by kirjavascript** [comment] 2024-10-08 13:40
Hi! Thanks for reporting this issue!

We're tracking this issue internally and will let you know when we have a resolution.

**Comment by plyght** [comment] 2024-10-31 14:07
> Hi! Thanks for reporting this issue!
> 
> We're tracking this issue internally and will let you know when we have a resolution.

@kirjavascript any updates on this?

**Comment by kirjavascript** [comment] 2024-10-31 14:13
We've been trying to improve on this in the background but due to the nature of the problem it's quite difficult to diagnose.

Could you try again from a fresh project, and let us know the prompts you used to get there?

**Comment by plyght** [comment] 2024-11-01 19:13
> We've been trying to improve on this in the background but due to the nature of the problem it's quite difficult to diagnose.
> 
> Could you try again from a fresh project, and let us know the prompts you used to get there?

@kirjavascript I have tried multiple projects; it mostly only happens when I ask for a portfolio site. It gets stuck right about when it tries to install idealtree builddeps. I think a good solution is to use https://bun.sh/ instead of npm, as it's abhorrently slow.
<img width="1593" alt="image" src="https://github.com/user-attachments/assets/1fb2e0cd-8198-47e0-81a4-47b53455af63">

**Comment by plyght** [comment] 2024-11-07 12:41
@kirjavascript any updates?

**Comment by fambrosoli1** [comment] 2024-11-11 10:01
same here

**Comment by flosrn** [comment] 2024-11-12 13:06
same here

**Comment by plyght** [comment] 2024-11-12 14:57
> @kirjavascript any updates?

@kirjavascript this seems like a prevalent issue that needs fixing. just following up!

**Comment by kirjavascript** [comment] 2024-11-12 15:01
There was an issue that appeared where `npm install` was not being run. We've since pushed out an update that improved on this, but there still appear to be issues.

Someone has been assigned to work on this, I will add a message here when we have an update on it!

**Comment by kirjavascript** [comment] 2024-11-12 18:45
actually, we just landed some improvements for fixing problems: https://x.com/stackblitz/status/1856399662351303017

maybe you could give it a whirl and let me know how it goes?

**Comment by Lifexcel** [comment] 2024-11-12 23:03
I am experiencing the same issue: an error occurs when I run `npm run dev`.

**Comment by egebese** [comment] 2024-11-13 20:21
It's impossible to run something. Npm install & run dev basically not working. Live preview in every project is empty blank screen. Spent 1M token for nothing.

![CleanShot 2024-11-13 at 23 20 32@2x](https://github.com/user-attachments/assets/d40ec727-921b-4853-ba9f-952a1eccaf90)

**Comment by jsscotty** [comment] 2024-11-14 09:27
My app worked fine but now also encounting this issue

**Comment by chrisdeweese** [comment] 2024-11-16 00:35
The only work-around I found for this issue at least for NextJS Vite projects is to delete the package-lock.json file, then manually run "npm install" and "npm run dev" in the terminal. Install takes forever, upwards of 15 minutes sometimes, but this fix consistently works, tested on multiple projects.

**Comment by FredFredericks** [comment] 2024-11-16 12:38
I am having the same issue and is taking a lot of tokens to fix :'D. Any updates?

**Comment by plyght** [comment] 2024-11-16 13:49
> actually, we just landed some improvements for fixing problems: https://x.com/stackblitz/status/1856399662351303017
> 
> maybe you could give it a whirl and let me know how it goes?

@kirjavascript This update hasn't seemed to help me, nor others. Is there anything more we can do to resolve this?

**Comment by jwillz7667** [comment] 2024-11-16 21:00
dude I want my money back from the subscription I purchased. if your product doesn't work yet you can't charge people for it

**Comment by rassu** [comment] 2024-11-18 10:09
Any update? Stuck here?

**Comment by plyght** [comment] 2024-11-18 13:23
> dude I want my money back from the subscription I purchased. if your product doesn't work yet you can't charge people for it

@kirjavascript It seems that this issue is affecting many, including paid, users. This is a major issue that needs resolving. How can we get this fixed?

**Comment by ronaold** [comment] 2024-11-18 13:25
> The only work-around I found for this issue at least for NextJS Vite projects is to delete the package-lock.json file, then manually run "npm install" and "npm run dev" in the terminal. Install takes forever, upwards of 15 minutes sometimes, but this fix consistently works, tested on multiple projects.

this doesnt work

**Comment by wtdavenport** [comment] 2024-11-18 21:47
I was excited to try Bolt and signed up for it today.  Running into the same problem with my first project.  I tried running nom install in terminal per the above sugggestion (after deleting package-lock.json) but terminal returned errors about "resolving the dependency tree".

**Comment by hlu38** [comment] 2024-11-19 13:32
Pareil , j'ai pris la solution payante et voici le resultat:

La commande a échoué
npm install

La commande a échoué
npm run stackblitz

**Comment by hlu38** [comment] 2024-11-19 13:34
Si il y a pas de support je vais résilier pour partir sur la solution open source.

**Comment by ricksinclair** [comment] 2024-11-20 00:27
Maybe this issue is due to a missing dependency being installed before the process starts. I can reproduce it consistently locally, but it doesn't crop up on the official site as much. 
<img width="493" alt="image" src="https://github.com/user-attachments/assets/b049f82f-642a-4af8-9601-066881db7518">
When I try to use angular on the bolt.new official service, it imports a dependency called bolt-angular. I'm guessing that provides an environment to pull a different set of packages. If I run the project locally, this dev dependency is never installed, and npm install related to angular doesn't work. I'm guessing this may be true for many dependencies.

**Comment by kc0tlh** [comment] 2024-11-20 00:36
**📣 Update** 
We have determined that for some users, this issue is due to using Safari or Firefox rather than Chrome or a Chromium browser. Safari & Firefox have limitations that make them unreliable for use with Bolt.new as described in #2796, and we are adding a warning banner to Bolt.new this week that alerts users to these potential issues.

**If switching to Chrome resolves your issue**, please let us know below.

**If switching to chrome does not resolve your issue**, please subscribe to #2021 for updates as @kirjavascript & the team will be  investigating additional causes of this error there! Appreciate your patience as we have been squashing bugs left and right and our small team is working as fast as we can!

CC: @magusonline @plyght @juancadile @Lifexcel @egebese @jsscotty @chrisdeweese @jwillz7667 @rassu @ronaold @wtdavenport @hlu38

**Closed by kc0tlh** 2024-11-20 00:36 UTC
Labels: tracked

**Comment by plyght** [comment] 2024-11-20 00:41
@kc0tlh Appreciate the (temporary) fix. Although, I should not need to switch the browser I am using, as this seems like an issue with bolt and not Safari or Firefox. I hope there will be a proper solution in the future. I do also appreciate the warning banner, as it shows real action taken here.

**Comment by kc0tlh** [comment] 2024-11-20 00:45
@plyght absolutely, and we 100% wish that Safari & Firefox would ship the needed features to support WebContainers (we have asked). Running an entire web dev OS in the browser really pushes the limits of current browser tech, and so far only Chrome has all the behind the scenes features needed 😢

**Comment by plyght** [comment] 2024-11-20 00:47
> @plyght absolutely, and we 100% wish that Safari & Firefox would ship the needed features to support WebContainers (we have asked). Running an entire web dev OS in the browser really pushes the limits of current browser tech, and so far only Chrome has all the behind the scenes features needed 😢

@kc0tlh well hopefully WebContainers are added to Webkit and Gecko soon. Again, I appreciate the work 🔥

**Comment by MadeByDouglas** [comment] 2024-11-20 09:50
Ok thanks for this, you really need to place the banner so users see this right away, i experienced this just now on safari and was quite frustrated until i found this thread.

Also, I'm wondering (besides waiting for Webkit to support web containers) if using bun or deno might solve this as well as generally make the experience faster and better.

**Comment by plyght** [comment] 2024-11-20 13:11
> Ok thanks for this, you really need to place the banner so users see this right away, i experienced this just now on safari and was quite frustrated until i found this thread.
> 
> Also, I'm wondering (besides waiting for Webkit to support web containers) if using bun or deno might solve this as well as generally make the experience faster and better.

@MadeByDouglas I second this! I love Bun, and it is super quick. Might be easier to use this. @kc0tlh

**Comment by rpiquerey** [comment] 2024-11-20 16:58
j'ai aussi le problem avec ns.

https://stackblitz.com/edit/sb1-1hhdwb?file=app%2Fapp.ts
`npm install && setup-nativescript-stackblitz && ns preview
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nativescript%2fsqlite - Not found
npm ERR! 404 
npm ERR! 404  '@nativescript/sqlite@^3.2.0' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /home/.npm/_logs/2024-11-20T16_57_21_519Z-debug-0.log`

il ne veux pas lancer ce projet, il date pourtant d'aujourd'hui malgré plusieurs tentative d'auto correction

**Comment by plyght** [comment] 2024-11-21 02:20
@rpiquerey Avez-vous essayé de passer de Safari ou Firefox à Chrome?

**Comment by blacklizardint** [comment] 2024-11-21 13:12
Same Exact issue on Mac OSX - Safari.  I spent 2 days burned through all tokens and never could get past the npm install error.  I was hoping this could be a new tool to use but...

**Comment by wtdavenport** [comment] 2024-11-21 14:51
Try Chrome and hopefully support will reset your tokens. Sent from my iPhoneOn Nov 21, 2024, at 8:13 AM, blacklizardint ***@***.***> wrote:﻿
Same Exact issue on Mac OSX - Safari.  I spent 2 days burned through all tokens and never could get past the npm install error.  I was hoping this could be a new tool to use but...

**Comment by shanky101** [comment] 2024-11-21 19:11
The same issue happened when i just asked bolt to generate a blog site using react. 
When I tried clicking on "Try to resolve problem", bolt editor went into an overdrive mode and code was getting rewritten and something happening in the background but at the end after 30 seconds of complete panic, the app gave up. Error never got fixed and I completely burned through my tokens! :(
Please at least add a banner or a warning. I'm hesitant to pay if tokens are burnt this way due to an app error. 
Browser - Edge on Mac (Chromium internally anyways)

**Comment by SuperTed2342** [comment] 2024-11-22 00:07
I asked Claude what to do and it said to use pnpm which seemed to work for a while. 

I'm using Chrome and it's back to looping install errors. V annoying.

**Comment by SuperTed2342** [comment] 2024-11-22 11:16
> I asked Claude what to do and it said to use pnpm which seemed to work for a while.
> 
> I'm using Chrome and it's back to looping install errors. V annoying.

@kirjavascript Are there any workarounds? I paid for bolt yesterday and will cancel this afternoon as it doesn't work.

**Comment by blacklizardint** [comment] 2024-11-22 15:24
I just opened back up today in Mac OS - Chrome and seems to be working.   Thanks @wtdavenport !!!

**Comment by chrisknu** [comment] 2024-11-22 19:12
Same error:
~/project 4s
❯ npm run dev

> generative-component-builder@0.0.0 dev
> vite
![Screenshot 2024-11-22 at 1 52 08 PM](https://github.com/user-attachments/assets/67e7b869-9345-45a9-b907-0fdf44caba0e)

`jsh: command not found: vite`

**Comment by goodyfab** [comment] 2024-11-22 23:21
Same here. Blasted though 3m tokens. very disappointing. Not sure how to run on a non-safari browser on iOS?!

**Comment by goodyfab** [comment] 2024-11-22 23:31
With "npm install", the QR code to launch the NativeScript app does not work. Unable to launch the app on my phone.
![IMG_7F52FDF89964-1](https://github.com/user-attachments/assets/73ff2e75-4daa-49f7-9eda-f58aa374a1c1)

**Comment by magusonline** [comment] 2024-11-22 23:33
Why is this "closed". It hasn't been resolved lol

**Comment by wtdavenport** [comment] 2024-11-23 06:57
Just download Chrome, login to Bolt with Chrome, and see if that resolves the issue. It did for me.

**Comment by goodyfab** [comment] 2024-11-23 17:05
Using Bolt with Chrome seems to have resolved the npm install issue for me as well.

**Comment by Jamie97419** [comment] 2024-11-24 18:05
Using Bolt in Chrome and the issue is still present... any help on the 2 issues...??
setup-nativescript-stackblitz && ns preview
&
npm install

**Comment by FredFredericks** [comment] 2024-11-24 18:44
Yo peeps! Try deleting the lock.json and manually npm install vite in the terminal. Also try npm--legacy-peer or npm --force. Worked for me after experiencing the same issue in Visual Studio. Hope it helps! Peace

**Comment by TinyLockwood** [comment] 2024-11-26 12:50
Using Bolt in Chrome (Version 131.0.6778.86) and the issue is still happening

npm install
&
npm run preview

is there any fixes out there?
![Screenshot 2024-11-26 124810](https://github.com/user-attachments/assets/0f6b7015-7da6-4efd-aa29-57be3a730929)

**Comment by kevingsp** [comment] 2024-11-26 23:10
same issue with Arc previewing with NativeScript

**Comment by plyght** [comment] 2024-11-27 02:47
@kc0tlh Please re-open this Issue, as there has been a _temporary_ fix, while not actually fully solving this issue.

**Comment by shawnurquhart** [comment] 2024-11-27 15:01
Yes this issue still exists currently - having same issue.

**Comment by mendoanjoe** [comment] 2024-11-27 19:18
Hello i getting this
<img width="1061" alt="Screenshot 2024-11-28 at 02 17 55" src="https://github.com/user-attachments/assets/ca7d1c16-3c3e-4a14-8cfd-5dfa33c20987">

**Comment by plyght** [comment] 2024-11-27 20:20
@mendoanjoe I believe that issue isn't related to this issue.

**Comment by devlk** [comment] 2024-11-28 04:24
Hi 👋,

As mentioned earlier, I was testing with the Chrome browser and encountered two issues:
1️⃣ Errors during npm install and npm run.
2️⃣ The Preview showed a blank screen (just a white page).

Here’s what I did to troubleshoot:
🔧 Deleted the package-lock.json file.
🔧 Manually ran npm install in the terminal, followed by ng serve.
✅ This resolved the installation and run errors, but the preview remained blank.

To investigate further, I switched to Firefox 🦊 (since I had been using Chrome previously).
🎉 The application worked perfectly in Firefox!

💡 I suspect the issue is browser-specific and likely related to the issue facing.

Hope this helps too and kudos to the  @wtdavenport for the tip.

**Comment by mccutch22** [comment] 2024-11-28 05:10
same issue (in firefox as well)

**Comment by mendoanjoe** [comment] 2024-11-29 02:41
> @mendoanjoe I believe that issue isn't related to this issue.

I think its related, its because npm has issue on install dependency with --legacy-peer-deps. If using bun that problem get solved

**Comment by plyght** [comment] 2024-11-29 19:04
> @kc0tlh Please re-open this Issue, as there has been a _temporary_ fix, while not actually fully resolving this issue.

@kc0tlh just following up on this.

**Comment by krp2203** [comment] 2024-12-01 20:08
having the same issue, both in Firefox and in Chrome. At one point I got Native Script to connect to my test phone but only got a blank screen

**Comment by steveorlosky** [comment] 2024-12-02 19:55
I'm also having the same issue! I'm using Chrome on Windows.

**Comment by blhouston** [comment] 2024-12-03 03:56
And my axe ... same issue. Chrome on Mac.

**Comment by shawnurquhart** [comment] 2024-12-03 05:59
Just tried myself and NPM is getting past dependancies install - just won't run for following error...

❯ npm start
> health-app@0.0.0 start
> ng serve
Error: This command is not available when running the Angular CLI outside a workspace.

Do you really need to use Angular. You could try another approach for now...

See screen shots

![errors - others - angular cli issue 1 ](https://github.com/user-attachments/assets/d006cfe4-9946-424b-851f-aafbc037372f)

![errors - others - angular cli issue 2 ](https://github.com/user-attachments/assets/0df11b5f-df3b-4557-994c-d56b6edc9326)

**Comment by magusonline** [comment] 2024-12-03 18:28
This problem is still not fixed. I even made a fresh new project and did it all in Google Chrome from start to finish. This error should not be closed so eagerly. 

I'm glad I unsubscribed to Bolt if this is their approach to the solution. I'm just making a new project and am reaching the same exact error, and it's an even simpler project, completely unrelated to the previous one. It generated the error on the very first prompt.

**Comment by dkfinkbone** [comment] 2024-12-03 19:06
I have tried to build three projects. I managed to get one to publish but had to strip out a bunch of functionality in the app. The other two just cant get passed the NPM RUN BUILD

**Comment by Nick-Sheridan** [comment] 2024-12-05 02:29
Please reopen this issue, several of us are still experiencing it.

**Comment by Beyud-ATT** [comment] 2024-12-05 06:28
i also face this problem, this should be an urgent bug to fix...

**Comment by goodyfab** [comment] 2024-12-05 15:28
Where can I CANCEL SUBSCRIPTION?
The instructions below indicate a "Manage Subscriptions" section, which I
don't see. Is there an updated location to cancel?

To cancel a Bolt.new subscription, open the Bolt app, go to your profile
settings, navigate to "Subscriptions" or "Manage Subscription," and then
select "Cancel Subscription."

**Comment by RJClarke** [comment] 2024-12-05 22:34
just checking in to see that... This is still closed? I can't run a single project because it's always fighting the npm install problem, and can't self correct

**Comment by plyght** [comment] 2024-12-05 23:10
> just checking in to see that... This is still closed? I can't run a single project because it's always fighting the npm install problem, and can't self correct

Yes, unfortunately @kc0tlh hasn't reopened this issue, even though this is quite a prevalent issue that causes many users issues and causes them to waste their money.

**Comment by mhspadez** [comment] 2024-12-06 18:49
Same issue here, I submitted a ticket to just see if I could at least get some credits back at least, although a fix would be great, and maybe try some of the fixes people have mentioned on this thread --- but no response yet, we'll see.... Is there a way we can run the install manually some how? Or upload the dependency files?

**Comment by Tarik37** [comment] 2024-12-12 16:26
Farwell!!

**Comment by plyght** [comment] 2024-12-13 17:22
> Farwell!!

Yeah, I've switched to [v0](https://v0.dev), and it's been wonderfully smooth and quality. So much better than bolt

**Comment by 23Antron23** [comment] 2024-12-15 14:00
Hello, anyone out there... we seemingly cant get past this error.. any devs watching?? what is the resolution esp for paying subscribers!..

**Comment by magusonline** [comment] 2024-12-15 14:05
> Hello, anyone out there... we seemingly cant get past this error.. any devs watching?? what is the resolution esp for paying subscribers!..

The solution at the moment is to vote with your wallet. Aka unsubscribe, at least that's what I've done. Just using up the remaining credits on other small things and side projects. 

The developers were extremely quick to close this issue within 24 hours and said that they will have a solution. But they didn't, their "switch browsers" one yielded nothing

**Comment by 23Antron23** [comment] 2024-12-15 14:13
Hmm had high hopes following youtube video.. alas have you found any other similar sites offering AI build-to-release platforms worthy of note?

**Comment by magusonline** [comment] 2024-12-15 14:16
I suppose it depends on how much backend programming you're familiar with. Since you'll still need to know how to implement auth0 and any other hooks to supbase if you're trying to monetize.

You could try 

https://lovable.dev/

Or download Windsurf AI or try v0.dev (same thing as this but came before)

**Comment by magusonline** [comment] 2024-12-15 14:17
> Hmm had high hopes following youtube video.. alas have you found any other similar sites offering AI build-to-release platforms worthy of note?

I suppose it depends on how much backend programming you're familiar with. Since you'll still need to know how to implement auth0 and any other hooks to supbase if you're trying to monetize.

You could try

https://lovable.dev/

Or download Windsurf AI or try v0.dev (same thing as this but came before)

**Comment by dmenchaca** [comment] 2024-12-18 16:40
Npm install still failing.

<img width="530" alt="Screenshot 2024-12-18 at 17 40 14" src="https://github.com/user-attachments/assets/59c348fb-594b-4efd-8acc-13a681f387b4" />

**Comment by i5hi** [comment] 2024-12-20 21:50
i get the same issue when create a Vue site. `vite build` fails because its not being installed globally.

**Comment by gxmech** [comment] 2024-12-27 03:58
Bolt is not ready for prime time.  Keep looking, new AI Agents appearing everyday!

**Comment by vikas-bluboy** [comment] 2024-12-28 11:28
without any resolution, how can the ticket get closed??

**Comment by mmad2021** [comment] 2024-12-28 18:34
just wasted almost 1mn tokens due to this issue

**Comment by frexe1** [comment] 2024-12-30 11:00
jsh: command not found: setup-nativescript-stackblitz


![image](https://github.com/user-attachments/assets/ad66dbb9-4966-4560-b488-6b558f174113)

**Comment by gabe-almeida** [comment] 2025-01-02 01:13
This bug is so insanely annoying.

**Comment by pchretien** [comment] 2025-01-04 15:23
> The only work-around I found for this issue at least for NextJS Vite projects is to delete the package-lock.json file, then manually run "npm install" and "npm run dev" in the terminal. Install takes forever, upwards of 15 minutes sometimes, but this fix consistently works, tested on multiple projects.

@chrisdeweese thanks for the tip ... I tried only deleting the package lock file and asked Bolt to fix the issues once more and it worked in a couple seconds.

**Comment by K155MY4R53** [comment] 2025-01-05 17:48
I too am running into this issue.

**Comment by digimarktech** [comment] 2025-01-10 04:51
Same issue still exists today

**Comment by protomota** [comment] 2025-01-12 17:20
This bug is not closed. Still happens today consistently on multiple products.

**Comment by harleyfr** [comment] 2025-01-13 20:18
Wasted tonnes of credits on this, can't finish my project til issue resolved. 
Please re-open this issue

**Comment by pchretien** [comment] 2025-01-13 21:34
More context ... in my case, when providing a long prompt at creation I get conflicts in the npm packages resulting in an error at npm install. I am using Angular. As an example, starting an Angular project with Firebase User management fails every time.

Option #1: Start a project with a small prompt with only the framework and a general idea of the project. Then add Firebase User Management and Database. Works every time. 

Option #2: Ask Claude 3.5 to fix the packages dependencies for me. Make sure to ask bolt to do what Claude suggest or it will be lost the next time Bolt change the package.json file.

I understand these are not ideal solutions but it saved me a ton of tokens.

**Comment by ANGio32** [comment] 2025-01-15 21:34
Use chrome

**Comment by plyght** [comment] 2025-01-15 21:56
@ANGio32 That is not a valid solution to this issue. We should be able to use whatever browser we choose, and not waste thousands of credits/money on not knowing about this error.

**Comment by PassionRose** [comment] 2025-01-24 18:21
this issue is still there and i cant push my project to deploy

![Image](https://github.com/user-attachments/assets/fd1153d5-43bf-4963-a090-5116dd4da9f3)

**Comment by magranero** [comment] 2025-02-07 09:37
I solved this similar problems:

Ask Bolt:

"Tell me what framework / template are this project built in"
BLABLA
"OK, then, check .built folder and config.json file and check if values of the template are ok with BLABLA framework.

Solved!

**Comment by kevin-flynnn** [comment] 2025-02-13 09:39
guys, bolt cant solve "npm install", i just manually test install package in local, then replace to bolt and it work !

**Comment by yebenesjose** [comment] 2025-02-25 17:42
![Image](https://github.com/user-attachments/assets/1785a32a-2f8d-41d1-b21c-90cb729415aa)

![Image](https://github.com/user-attachments/assets/408313c6-cede-4b99-bf76-36837d6221af)

for astro projects its getting stuck in the initial npm instal setup too.

**Comment by Gems** [comment] 2025-03-03 16:11
Switch from Safari to another browser helped! Guys, read the message buried in the hidden part of this thread.

**Comment by ChrisGrannell** [comment] 2025-03-14 03:13
> Use chrome

I don't understand this, but it seems to fix it. If Safari is that much of a problem I would suggest that the good people at Bolt block Safari. I have wasted a few hours unnecessarily here.

**Comment by mikebigshot** [comment] 2025-03-14 19:22
Still an issue. I’ve literally never been able to create a single project with bolt because of this. EVERY project gets stuck installing dependencies. Why am I paying for this? How do other people ever get it to work? I don’t get it.

**Comment by mrymsadeghi** [comment] 2025-03-19 05:38
I found a solution.
In the code preview, bottom click on Terminal and run
Yarn install.

It'll work after the installation is done

**Comment by waftad** [comment] 2025-03-26 05:43
I applied the yarn install and reran the update but still have the same problem. using Google chrome

**Comment by Edurebello** [comment] 2025-03-26 14:17
Mesma coisa por aqui, dá erro no Npm install e não consigo utilizar por que para a resolução do problema se gasta credito, porém não é resolvido.

**Comment by waftad** [comment] 2025-03-26 17:57
> Mesma coisa por aqui, dá erro no Npm install e não consigo utilizar por que para a resolução do problema se gasta credito, porém não é resolvido.
Don’t waste your money, it will not resolve the code

**Comment by PassionRose** [comment] 2025-03-30 19:08
still having the same issue in-spite all of the above trails!

**Comment by CryptoVoiceGuy** [comment] 2025-04-10 09:43
This still doesnt work?? What are you doing to fix this

**Comment by AndyatFocallocal** [comment] 2025-04-14 15:13
I'm also in this boat. Wanted to sign up, but can't if it gets stuck here every app i try to build.

**Comment by magusonline** [comment] 2025-04-16 20:48
> This still doesnt work?? What are you doing to fix this [@kirjavascript](https://github.com/kirjavascript)

They aren't going to fix it. I have long since unsubscribed from Bolt.new  
They closed the issue without any testing. 
The same way I closed my account without any regret.
It doesn't help that there's no way to reopen the issue.  
And they'll just automatically close all new issues on it.

**Comment by Xseron** [comment] 2025-04-17 07:19
have same issue

**Comment by vanquishcode** [comment] 2025-04-18 14:05
Are you moving to another solution instead of Bolt.new? I am having the same issue

**Comment by erwanmichalet** [comment] 2025-04-18 14:17
Same here....

**Comment by mikebigshot** [comment] 2025-04-23 19:31
> Are you moving to another solution instead of Bolt.new? I am having the same issue

Lovable. I want bolt to work so badly for me but this is such a weak problem that I can’t believe it still exists.

**Comment by plyght** [comment] 2025-04-23 20:02
> Are you moving to another solution instead of Bolt.new? I am having the same issue

@vanquishcode I'm either using https://v0.dev or https://lovable.dev

I've also heard of https://chef.convex.com

**Comment by Enjo-Init** [comment] 2025-04-25 05:36
I'm left thinking that it might be an issue to do with **knowledge cut-off** point on the AI model they are using. This means however much you try to patch it, it organically reverts back some de'facto settings and way of problem solving that end up messing everything or even worsening the problem. We might have to wait for an update to the core AI model in order to move ahead with our projects.

**Comment by soeren-mj** [comment] 2025-05-03 00:28
Does it mean every client has this issue?

**Comment by adeelhasan** [comment] 2025-05-05 18:38
I am also having the same issue, and I also bought new credits so that it could continue. I want a refund, I am trying it out for the first time, its not a local install either, so this issue is entirely on them.

**Comment by maciejmaciejmaciejmaciej** [comment] 2025-05-07 16:10
100h wasted

**Comment by adeelhasan** [comment] 2025-05-07 18:30
my resolution was start all over again, and to build more slowly, and then to use the "Rollback" feature or to restore from Backups feature where needed. I think if bolt cannot fix it in a couple of tries, then you have to take a closer look or to try a different approach. In my case I could start again, so was lucky, but it's very uncertain if I can complete the project if there is this volatility in how it's going to behave. Some people take the stackblitz project to cursor to try and fix issues.
