### ISSUE TITLE
Bolt crashes on Error: Failed to execute “insertBefore” on “Node”

### ISSUE THREAD

**Issue by endocytosis** [stackblitz/bolt.new#2556] opened 2024-11-17 00:05 UTC
**Issue:** Users report application breaking error. Collecting similar cases here for further investigation.

**Comment by AriPerkkio** [comment] 2024-11-27 09:54
This issue comes up when users' browser plugins, such as Google Translate, modify the `bolt.new` page. At the root the cause is in React: 
- https://github.com/facebook/react/issues/11538

We've already shipped couple of fixes in erroneous elements so most of the linked issues should be fixed already. We are also looking into improving error handling so that users would not lose their work when errors like this come up.

**Closed** 2024-12-20 11:55 UTC
Labels: Linear Created
