### ISSUE TITLE
[URGENT] Major Issue: Bolt not saving chats or builds

### ISSUE THREAD

**Issue by mauriciorubio2** [stackblitz/bolt.new#160] opened 2024-10-07 14:39 UTC
### Describe the bug

Bolt is not saving chat history or builds in my account. And I'm on a paid account. This is a major issue because why would anyone spend hours building something and then log back in to find nothing?
Can someone please fix this ASAP?
Is there any way you can help me recover everything I've built?

Not sure if this issue is being caused because I signed up to Bolt using my Github credentials, but I don't think it should matter how you sign up, you should never lose your work

### Link to the Bolt URL that caused the error

https://stackblitz.com/@mauriciorubio2

### Steps to reproduce

If you check my account, you won't find any chat history, yet I have built many apps, including one which I shared in this post: https://x.com/_mauriciorubio/status/1842529786767499475

### Expected behavior

Chat history remains in your account. If you manually delete a chat, it should be sent to a Bin which you can recover for at least 30 days.
Things you've built don't disappear, but remain so you can continue working on them later on

### Platform

- OS: macOS
- Browser: Brave

**Comment by mauriciorubio2** [comment] 2024-10-07 14:47
I'm hoping someone at Bolt/Stackblitz can help me recovering my work, because I spent hours on this and definitely don't want to lose my progress. This and versioning (being able to easily roll back to a point before you made additional changes) are incredibly important and fundamental things. Who wants to work on something and then log back in to see nothing? Makes no sense at all

**Comment by temakubik** [comment] 2024-10-07 16:52
Also chats are disappearing (

**Comment by Nemikolh** [comment] 2024-10-07 19:09
Hey we understand your frustration but creating more issues won't help! :sweat_smile: 

I'll close this issue as this is already tracked as part of https://github.com/stackblitz/bolt.new/issues/39

**Closed by Nemikolh** 2024-10-07 19:09 UTC

**Comment by samdenty** [comment] 2024-10-16 20:59
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50

**Comment by mmad2021** [comment] 2024-12-01 03:28
I got this experience with free plan. Then I tried paid plan. And still got this issue. And now my hours of works is gone. Can you also help find out root cause and if it's possible to recover mine? Because it happened to me with a paid plan also.

**Comment by joelyan00** [comment] 2025-02-20 16:29
my chat is also lost, I am a paid user, and I spend a almost 100 dollor to build my app, it took me one month job, then today I am want to open my project to keep working, but it lost. I need bolt to pay me work and my lost.

**Comment by LukaBanovic** [comment] 2025-03-03 08:18
@kc0tlh My chats are lost, projects are seen on Stackblitz, but fail to import into Bolt. 

This is critical and drastically blocking people's work life. When are we to expect a fix?
