### ISSUE TITLE
Urgent: Project Files Missing/Overwritten

### ISSUE THREAD

**Issue by Jedimind369** [stackblitz/bolt.new#571] opened 2024-10-14 14:03 UTC
Dear Support Team,

I'm experiencing a critical issue with my project that I started yesterday. All of my original work seems to have disappeared or been overwritten. Here's what I've observed:

1. Current State:
   - I only see a basic Node.js project structure with a simple package.json and index.js file.
   - The package.json file contains only default configurations.
   - The index.js file only has a "Hello, Node.js!" console log.

2. Expected State:
   - I had a more complex project that I worked on yesterday.
   - [Advanced-Bookmark-Management-System-with-React-and-TypeScript]

3. Issues:
   - All my original work from yesterday is missing.
   - I can't find any of the files I created or modified yesterday.
   - The current files seem to be from a basic Node.js starter template.

4. Questions:
   - What happened to my original project files?
   - Is there any way to recover my work from yesterday?
   - Why was my project reset or overwritten?
   - How can I prevent this from happening in the future?

This situation is severely impacting my work, and I urgently need assistance in recovering my lost files or understanding what happened.

Please advise on next steps or any actions I can take to recover my work.

Thank you for your prompt attention to this matter.

Alex

**Comment by kc0tlh** [comment] 2024-10-21 19:19
Apologies for this frustrating experience!

While there is a bug affecting a small number of free users (see below for more info) it is possible that what you are experiencing is simply related to our current limited chat persistence model. Chat history is currently not persisted across browsers/devices, and chats will disappear from the Bolt.new UI if your cache is cleared, so it is possible that your project was actually saved to StackBlitz behind the scenes. If that is the case, you can find your project on [StackBlitz.com](http://stackblitz.com/) (same account as Bolt.new) > Collections Tab > Bolt collection. If this is you, we are landing improved chat persistence in 1-2 weeks and you can track that in issue 39.

Unfortunately, If your project is not stored there, then it is likely you are experiencing the bug described below:
Our engineering team has been looking at the logs and links that were provided related to this issue (thanks for providing these) and we have identified a root cause affecting a small number of users on our free tier rate limits. We are shipping a fix now (updates on that to come in the main issue #50) but unfortunately are unlikely to be able to recover projects that ran into this error. 

While bugs can happen during beta periods, we are sorry that you experienced this! I want to thank everyone that reported this issue and provided project links and information as it was key in identifying and resolving this issue for everyone going forward 🙇

**Closed by kc0tlh** 2024-10-21 19:19 UTC

**Comment by Jedimind369** [comment] 2024-10-21 20:42
Thank you for your response and the explanation of the potential causes for my project disappearance. However, I want to clarify a crucial point that wasn't addressed in your reply:

I was not a free-tier user when this incident occurred. I had a paid plan with Bolt.new, which makes this situation even more concerning. As a paying customer, I expected a higher level of service reliability and data protection.

Given this information, I have some additional questions and concerns:

1. Are paid users also affected by the bug you mentioned, or is this a separate issue?
2. What specific data recovery options are available for paid users who experience project loss?
3. What is the refund policy for paid users who suffer significant data loss due to platform issues?
4. Is there a dedicated support channel for paid users to address critical issues like this?
5. What measures are being taken to prevent such data loss incidents for paid users in the future?

I appreciate your efforts to address the free-tier issues, but I believe my situation as a paid user warrants additional attention and a more comprehensive response. The loss of my project has significantly impacted my work, and I'm seeking a resolution that reflects my status as a paying customer.

I look forward to your response addressing these specific concerns. Thank you for your attention to this matter.
