### ISSUE TITLE
Ai re-writes whole app just to fix an error

### ISSUE THREAD

**Issue by ashhwheeler** [stackblitz/bolt.new#599] opened 2024-10-15 13:52 UTC
### Describe the bug

When prompting a fix to the app that i spent a couple prompts building the ai attepts to fix the bug by rebuilding the entire web app and re writing the front end ui that i built. Having to explicitly explain not to change anything on the ui and only fix the error each prompt.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-rabwea

### Steps to reproduce

1. Prompt to build an app. 4-5 prompts deep.
2. Error pops up (API input needed)
3. User adds api key
4. Asks app to fix errors
5. AI fixes errors and rebuilts ui of the app
6. Ai was not propmted to rebuild the UI
7. User needs to revert back again and start trouble shooting and re prompting. 

### Expected behavior

When i ask to fix the error that the AI only fixes the error and does not redesign and re code the entire app and all the a pages along with it.

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 53911339,
  "usedJSHeapSize": 49884727,
  "jsHeapSizeLimit": 4294705152
}
Username = ashhwheeler
Chat ID = 8d6bc4e5d9e3
```

**Comment by benspak** [comment] 2024-10-15 13:56
I've been running into the same issue. Frustrating..

**Comment by SharadKumar** [comment] 2024-10-15 16:18
I built an app for 4 hours and then one glitch lost most of my work. Now I cant rollback to previous working state!!! No matter what.

**Comment by Jpubli** [comment] 2024-10-15 16:20
It´s really annoying. Be careful with your tokens cause any simple change will consume lots of them. @stackblitz-gitops could you help?

**Comment by mawiskored** [comment] 2024-10-15 18:00
Same problem. I submitted a ticket a week ago and no response.

**Comment by ericwelshdev** [comment] 2024-10-16 18:26
Same , same .. @stackblitz-gitops  Token consumption and code re-writing issues are seriously out of control - the simple fact that an allocated 10 million per month on a paid plan can be burned through in a matter of a few HOURS, most of which is do the code gen engine deciding to update and re-write files for no reason or introduces bugs of which in most cases additional prompting in efforts to fix the bugs it introduced causes more issues , coupled with the number of times it attempts to shortcut and comment code with stuff like // ... (keep all the existing constants) but not providing said code that had already existed which then breaks more issues that you cannot successfully undo or rollback ( keep in mind we are getting penalized for things that ai code generator does/breaks itself)  ... understandably there's going to be bugs like this during the early adoption phase however in order to keep folks on your platform working through these issues so as they are captured and addressed by @stackblitz-gitops  it would be suggestible that you either removed the token limits for paid users or find a way to keep folks working, testing and using your platform because if we can burn through our 10 million token allocation within a few hours that's supposed to last us a month then something is seriously wrong... 
As it sits some of us are in a position where we've paid for a plan , consumed all the allocated tokens and due to the ai code gen has left our work in an unusable state or lost all together...( to note - without the chat history to reproduce in a deterministic manner)  What is one to do at that point ? wait another month ? We can't purchase more tokens as that feature has been removed and even if we had the number of tokens the process consumes will put us right back where we started. 
As noted here as example : [Issue 448 ](https://github.com/stackblitz/bolt.new/issues/448)

FYI Not hatin, I think this platform has some incredible potential and has been one of the better code gen ai platforms I've seen ( just need to work through the few of the early adoption pains - @stackblitz-gitops @EricSimons i know you guys are geniuses and can do it ! This has been a frustrating but very cool experience !

**Comment by EricSimons** [comment] 2024-10-16 18:37
Hi all- we actually just [posted a thread](https://x.com/stackblitz/status/1846607152267645136) on this about the WIP we have that will help address these errors, specifically:

- [breaking error loops](https://x.com/stackblitz/status/1846607153790177655)
- [controlling what the AI can & cannot edit](https://x.com/stackblitz/status/1846607155530813598)
- [a "require approval before AI changes code" mode](https://x.com/stackblitz/status/1846607157258866938)
- [& reducing avg token usage per message](https://x.com/stackblitz/status/1846607158609432723)

All landing over this week & next, ETAs for each included in thread!

**Comment by kc0tlh** [comment] 2024-10-22 19:59
@ashhwheeler @Jpubli @benspak @mawiskored @ericwelshdev please follow issue #678 for continued updates on this topic.

**Closed by kc0tlh** 2024-10-22 19:59 UTC
