### ISSUE TITLE
Chat Projects are being deleted

### ISSUE THREAD

**Issue by jbratton45** [stackblitz/bolt.new#583] opened 2024-10-14 21:00 UTC
### Describe the bug

twice my chat projects have disappeared. I have enough tokens 26M. Money and time wasted. I'm hoping to get feedback. Starting to feel like I'm screaming in Space 

### Link to the Bolt URL that caused the error

URL missing

### Steps to reproduce

Log in and my chats are gone

### Expected behavior

Expect my chats to be saved

### Screen Recording / Screenshot

Chrome 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by bmlorio** [comment] 2024-10-15 01:02
perdi el desrrollo de toda una semana, el link para hacer un primer deploid que me dieron fue este: https://sunny-bubblegum-9cc077.netlify.app/ y este otro https://velvety-snickerdoodle-2313ca.netlify.app/.
Es lo unico que tengo. No entiendo que paso

**Comment by kc0tlh** [comment] 2024-10-16 22:50
Apologies for this frustrating experience!

While there is a bug affecting a small number of free users (see below for more info) it is possible that what you are experiencing is simply related to our current limited chat persistence model. Chat history is currently not persisted across browsers/devices, and chats will disappear from the Bolt.new UI if your cache is cleared, so it is possible that your project was actually saved to StackBlitz behind the scenes. If that is the case, you can find your project on [StackBlitz.com](http://stackblitz.com/) (same account as Bolt.new) > Collections Tab > Bolt collection. If this is you, we are landing improved chat persistence in 1-2 weeks and you can track that in issue 39.

Unfortunately, If your project is not stored there, then it is likely you are experiencing the bug described below:
Our engineering team has been looking at the logs and links that were provided related to this issue (thanks for providing these) and we have identified a root cause affecting a small number of users on our free tier rate limits. We are shipping a fix now but unfortunately are unlikely to be able to recover projects that ran into this error. We are working as I type this to ship the fix!

While bugs can happen during beta periods, we are sorry that you experienced this! I want to thank everyone that reported this issue and provided project links and information as it was key in identifying and resolving this issue for everyone going forward 🙇

**Closed by kc0tlh** 2024-10-16 22:50 UTC
