### ISSUE TITLE
Project Not Found !!!

### ISSUE THREAD

**Issue by davidmoshal** [stackblitz/bolt.new#333] opened 2024-10-09 22:06 UTC
### Describe the bug

Project disappeared during a chat

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-lxf6v2

### Steps to reproduce

Not sure how to replicate this, and honestly don't want to make another project disappear!

### Expected behavior

projects should not disappear
<img width="562" alt="Screenshot 2024-10-09 at 3 05 50 PM" src="https://github.com/user-attachments/assets/efad2896-6a3e-4408-974d-372db759dc8f">

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 47336796,
  "usedJSHeapSize": 44741784,
  "jsHeapSizeLimit": 4294705152
}
Username = davidmoshal_4vzu
Chat ID = 3c00da7bb762
```

### Additional context

Error:
```
There was an error processing your request
```

**Comment by davidmoshal** [comment] 2024-10-09 22:13
Cancelled my Pro plan.

I lost a day's work after my project disappeared.
I was also unable to open the project in StackBlitz, so there was no way to save the project and now there is no way to recover it.

I will renew my plan if you can find my project, otherwise I'll continue with Cursor, Claude Dev, and Aider, and wait for the announcement that this platform is ready.

BTW: I have never lost a project with Cursor, Claude Dev, or Aider yet!

**Comment by Nemikolh** [comment] 2024-10-09 22:15
Hey @davidmoshal ! Really sorry for the issue.

It's possible that your project is not lost. Have you tried going on https://stackblitz.com ?

In there you should be able to see all your projects:

![image](https://github.com/user-attachments/assets/89bedca1-9056-43b3-a31f-e28cf99b7a86)

**Comment by davidmoshal** [comment] 2024-10-09 22:24
Nope it's not there. 

Note: Bolt.new projects don't MAGICALLY appear in stackblitz, you have to actually open them in stackblitz as far as I can tell. 

And that project lost the ability to be opened in stackblitz a few hours ago, see my prior bug report.

I'm noticing that you've had 300+ issues opened in about 3 days, that I think is a record on Github.

My point being: This project is not ready for prime time, and you should not be misleading users. I can guarantee you that I'm not the only one who is going to be extremely pissed off at losing a day of work.

So now, while originally this seemed superior to Claude Dev, Cursor, Aider, etc, etc, now, because of bad QA on your part, it's at the bottom of the heap. 
None of the others will lose your work like that.

The real problem here is that there is no way to version control Bolt.new projects, that's the issue you guys have to solve today. 

I mean seriously, you need to stop working on every other fancy feature and find a way to protect your users work. 

Today.

Currently in Bolt the best you can do is open the project in StackBlitz and "fork" it.
However:
a) not all projects can be opened in stackblitz, and 
b) once in stackblitz projects cannot be connected to Github unless it seems there is a pre-existing 'main' branch, at least that seems to be the error I'm getting.

**Comment by Nemikolh** [comment] 2024-10-09 22:33
> Note: Bolt.new projects don't MAGICALLY appear in stackblitz, you have to actually open them in stackblitz as far as I can tell.

@davidmoshal Actually they're persisted in the same service so your project should be visible in there. The open in stackblitz only provide a shortcut to show them.

> My point being: This project is not ready for prime time, and you should not be misleading users. I can guarantee you that I'm not the only one who is going to be extremely pissed off at losing a day of work.

I totally hear you and I'm really sorry this happened to you.

I've brought up your case with the rest of the team, I'll let you know if we can help in any way.

Thank you so much for trying us early, we really appreciate it!

**Comment by programmer22** [comment] 2024-10-09 22:43
I say we retailiate and take screenshots of all the issues and paste them on x, and let the public know they are not taking care of their customers and fixing the issues needed to be fixed. If they fix the issues, I will stop. But I will not let down and will post this comment on every github issue to make sure everyone is on board. Don't just let this go out the window, its your work. Its your data. Spread the word and save other developers.

**Comment by EricSimons** [comment] 2024-10-09 23:08
Y'all- I'm sorry about the bugs you experienced, but as advertised _this is a public beta_ - things _will_ break but we are working as hard as we can to fix them asap! If you cannot afford to encounter any bugs please wait a week or two while we stabilize amidst monster traffic 🙇

**Comment by EricSimons** [comment] 2024-10-09 23:10
Also, please don't threaten retaliation/etc against StackBlitz employees- these are good, hard working people doing their best to make a great product over here.

As StackBlitz CEO I take the well being and respect of my team seriously, and further threats like these will result in ban from this repo

**Comment by programmer22** [comment] 2024-10-09 23:18
I am not going to retaliate as I think what you guys are doing is great. But you have a lot of unhappy customers, and I hope this can get fixed soon and everyone can get their data back and retrieved. All I am asking for. If that happens, I will back you guys 100% until the end.

**Comment by davidmoshal** [comment] 2024-10-09 23:33
@EricSimons Firstly, great to see we have the CEO's attention, that's awesome.
Secondly I haven't threatened anybody, not sure if you're referring to me, all I did cancel my subscription, which I think you'll agree is understandable.

I totally understand that you guys are under pressure, you have a potentially awesome application, but you are charging for it right, you are asking folks to make an investment, and you are not disclosing any of the following:
1) that there is a risk you will lose all of you data.
2) that there is no way of versioning your data in the product, other than to open it in stackblitz and 'fork' it and/or download it.
3) that the ability to open it in stackblitz is buggy and you may not be able to do so

So a more honest approach would be to disclose that:
a) this is beta software
b) you may lose your data at any time.
c) the only way to save your work is to regularly open it in stackblitz and 'fork' it and/or download it, 
d) the ability to open it in stackblitz is also buggy and you may not be able to do that either.

I would suggest that you immediately focus on protecting your users work, their time and effort is not to be taken for granted.
 
I can't imagine it's difficult to allow folks to version, save, download directly from Bolt, I suspect the reason you don't want to do that is that you're not ready for bolt to handle user generate code or edits. That's fair enough and probably a good way to control code quality, at least for now, but somehow you should find a way to at least persist data in one direction reliably.

**Comment by EricSimons** [comment] 2024-10-10 00:11
Agreed and I made this exact statement + status of WIP w/ timelines over 48h ago fyi: https://x.com/ericsimons40/status/1843345406576787496

**Comment by EricSimons** [comment] 2024-10-10 00:31
> I can't imagine it's difficult to allow folks to version, save, download directly from Bolt, I suspect the reason you don't want to do that is that you're not ready for bolt to handle user generate code or edits

No, the actual reason is that we didn't have time to implement this is a robust way before launch day, and are now working as fast as we can to get it landed as a fast follow

**Comment by EricSimons** [comment] 2024-10-10 00:32
> Secondly I haven't threatened anybody, not sure if you're referring to me, all I did cancel my subscription, which I think you'll agree is understandable.

Yes this was not for you FYI! It was for the other commenter who has subsequently been blocked from all stackblitz repos after continuing threats/etc in other threads

**Comment by davidmoshal** [comment] 2024-10-10 01:44
Yep, he was out of line, that's for sure, and I was a bit uncomfortable that he jumped into this thread, he was not being productive at all.

Re this comment:
https://x.com/ericsimons40/status/1843345406576787496

I'd add that if you find that you can't open in Stackblitz anymore there you might have run into a bug that could get worse, you could lose the project in Bolt, so better to stop and pick up from your last Stackblitz checkpoint (or words to that effect)

In addition, I'm not sure how many folks expect to find the answers in X, maybe in the interim you should add something to the Bolt page explaining a couple of things, to save everyone time:

1) that currently there isn't a way to download the code from bolt directly, or to version it. 
Best you can do is open in Stackblitz and 'fork' it or download it.

2) There is the possibility that the project wont'd be persisted properly and could be lost, and sometimes it is preceeded by you being unable to open it in Stackblitz. So that would be good time to go back to a checkpoint.

3) Once the code is in Stackblitz you can't add it to github yet (I ran into a problem where it expects a 'main' branch I think, you can see my other bug report)

4) You can't edit the code directly in Bolt, but you can do it indirectly via the chat.

5) You can't open other Stackblitz projects in Bolt. (I'm actually not sure about that, for some projects I was able to do that, for others not)

**Comment by DIegolitoMatador1984** [comment] 2024-10-12 19:01
Im facing the same issue. and I lost a whole day of work :(

**Comment by samdenty** [comment] 2024-10-16 20:59
We've just found what the root cause to the loss of work bug is, we're going to ship a fix soon 👀 

we'll track this issue in https://github.com/stackblitz/bolt.new/issues/50

**Closed by samdenty** 2024-10-16 20:59 UTC

**Comment by anshul-031** [comment] 2024-11-22 04:00
@

This bug is affecting me too. Bolt.new does not offer the "Save project" option for the project to be saved. 

It seems like It indirectly saves the code on a local device & maybe periodically saves the project to the cloud. However, the periodic is problematic; we don't know this time period, whether it's 1 hour or 10 min. of idleness. But really, this is very problematic bug.

Mostly, whoever is using a bolt.new is generally a software developer, so if possible, till you fix this bug, Can you explain how the project is saved to the cloud works or some workaround so that we can make sure our project is saved in the cloud?

Or some way we can trigger saving of project in cloud?
