### ISSUE TITLE
Bug: AI replacing actual code with code comments like  // ...remaining code here

### ISSUE THREAD

**Issue by FastTrackAudio** [stackblitz/bolt.new#124] opened 2024-10-06 22:44 UTC
### Describe the bug

When making smaller changes to a file, the AI will just write in something like "This part of code stays the same" without actually keeping the code, they just replace it with a comment like

// ... (previous imports remain the same)

interface QuizTakerProps {}

const QuizTaker: React.FC<QuizTakerProps> = () => {
  // ... (rest of the component code remains the same, remove any usage of quizId)
}

export default QuizTaker

This breaks the application everytime and uses more tokens to fix, its been the only annoying part of going back and forth, even prompting it with "rewrite the entire file to ensure all code is there and the file is complete" only works 80% of the time. 

I know its hard, but it would be cool if it just modified the code that had to be modified, instead of rewriting the entire file from scratch. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-fkyaen

### Steps to reproduce

write an application that has any sort of complexity, then ask it to just make a minor change to part of it that doesn't affect one of the subparts of it. 

### Expected behavior

I expect the code that stays the same to still be there

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

I LOVE THIS TOOL, only reporting to make it better!

also, it doesn't tell me when my tokens refresh

**Comment by pk-pathkraft** [comment] 2024-10-22 08:06
i am also facing the same issue, i am building a WordPress plugin

initial prompts went find till a few versions, i was slowly prompting and adding more features, but after a while bolt started loosing the context , after inspection of the code i found that the main files the code were missing after a point of time and i was seeing this

// ... (rest of the code remains the same)

Which explains why there were errors and functionality loss, i tried various prompts to evade this loop
but not very successful .

i Lost a of lot of tokens and time trying to come over this issue,

**Comment by kc0tlh** [comment] 2024-10-22 20:22
**🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.

**Closed** 2024-10-29 21:24 UTC
Labels: bug, tracked

**Comment by Bogatinovski** [comment] 2024-11-10 05:34
Hi, I just experienced this issue last night. At first it was razor precise with generating all the React components accurately. But later after 5-6 hours of adding more and more features the build started breaking and when I inspected one of the larger files I saw these AI placeholder comments. Here's an example  of a file which is supposed to have 316 lines but it was truncated to this:

```
{/* Previous imports remain the same */}
import { 
  X, ArrowLeft, Wallet, CreditCard, Banknote, PiggyBank, Building, Car, Briefcase, Users, 
  GraduationCap, Home, Plane, Plus, ShoppingBag, Gift, Coffee, Utensils, Bus,
  Train, Bike, Smartphone, Laptop, Tv, Gamepad, Book, Music, Film, Camera, Heart, Star,
  Sun, Moon, Cloud, Umbrella, Zap, Target, Flag, Map, Compass, Globe, Package, Box,
  ShoppingCart, Tag, Ticket, Calendar, Clock, Bell, Mail, Phone, Printer, Tool, Key
} from 'lucide-react';

{/* Previous interfaces and types remain the same */}

const COLORS = [
  { name: 'emerald', value: '#34D399' },
  { name: 'amber', value: '#FBBF24' },
  { name: 'violet', value: '#A78BFA' },
  { name: 'rose', value: '#FB7185' },
  { name: 'cyan', value: '#22D3EE' },
  { name: 'orange', value: '#FB923C' },
  { name: 'teal', value: '#2DD4BF' },
  { name: 'red', value: '#EF4444' },
  { name: 'fuchsia', value: '#E879F9' },
  { name: 'indigo', value: '#818CF8' },
  { name: 'lime', value: '#84CC16' },
  { name: 'sky', value: '#0EA5E9' },
  { name: 'purple', value: '#A855F7' }
];

const PRESET_ICONS = [
  { icon: Wallet, label: 'Wallet' },
  { icon: CreditCard, label: 'Credit Card' },
  { icon: Banknote, label: 'Cash' },
  { icon: PiggyBank, label: 'Savings' },
  { icon: Building, label: 'Bank' },
  { icon: Car, label: 'Car' },
  { icon: Briefcase, label: 'Business' },
  { icon: Users, label: 'Personal' },
  { icon: GraduationCap, label: 'Education' },
  { icon: Home, label: 'House' },
  { icon: Plane, label: 'Travel' },
  { icon: Umbrella, label: 'Emergency' },
  { icon: ShoppingBag, label: 'Shopping' },
  { icon: Gift, label: 'Gift' },
  { icon: Coffee, label: 'Coffee' },
  { icon: Utensils, label: 'Food' },
  { icon: Bus, label: 'Bus' },
  { icon: Train, label: 'Train' },
  { icon: Bike, label: 'Bike' },
  { icon: Smartphone, label: 'Phone' },
  { icon: Laptop, label: 'Laptop' },
  { icon: Tv, label: 'TV' },
  { icon: Gamepad, label: 'Gaming' },
  { icon: Book, label: 'Education' },
  { icon: Music, label: 'Entertainment' },
  { icon: Film, label: 'Movies' },
  { icon: Camera, label: 'Photography' },
  { icon: Heart, label: 'Health' },
  { icon: Star, label: 'Favorites' },
  { icon: Sun, label: 'Utilities' },
  { icon: Moon, label: 'Night' },
  { icon: Cloud, label: 'Cloud' },
  { icon: Zap, label: 'Energy' },
  { icon: Target, label: 'Goals' },
  { icon: Flag, label: 'Milestone' },
  { icon: Map, label: 'Location' },
  { icon: Compass, label: 'Navigation' },
  { icon: Globe, label: 'Global' },
  { icon: Package, label: 'Package' },
  { icon: Box, label: 'Storage' },
  { icon: ShoppingCart, label: 'Cart' },
  { icon: Tag, label: 'Tag' },
  { icon: Ticket, label: 'Ticket' },
  { icon: Calendar, label: 'Calendar' },
  { icon: Clock, label: 'Time' },
  { icon: Bell, label: 'Notification' },
  { icon: Mail, label: 'Mail' },
  { icon: Phone, label: 'Contact' },
  { icon: Printer, label: 'Office' },
  { icon: Tool, label: 'Tools' }
];

{/* Previous component code remains the same until the icon button */}

<button
  type="button"
  onClick={() => setIsIconPickerOpen(!isIconPickerOpen)}
  className={`wallet-type-icon ${customization.iconColor} relative group`}
>
  <SelectedIcon className="w-6 h-6 text-white transition-opacity duration-200 group-hover:opacity-0" />
  <div className="absolute inset-0 flex items-center justify-center">
    <span className="text-white text-sm font-medium opacity-0 group-hover:opacity-100 transition-opacity duration-200">
      Change
    </span>
  </div>
</button>

{/* Rest of the component code remains the same */}
```

**Comment by Bogatinovski** [comment] 2024-11-25 17:31
@kc0tlh Please reopen this issue. This is a high-priority issue which you claim to have been solved but myself (and many other) are still consistently facing this issue. I have wasted millions of tokens revering the code and asking the AI model explicitly not the do this. Even so, sometimes it doesn't "listen" even if I explicitly tell it not to replace actual code with placeholder comments.

**Comment by Ekpap** [comment] 2024-11-27 14:09
@kc0tlh Hey Chief Alexander, I'm +1 on this issue. Bolt just comments out code indefinitely now (granted my file is pretty long). Will be discontinuing bolt subscription if this continues b/c it's essentially turning into a chatGPT copy-paste code editor, which I have for free already.
It does seem like a tough issue because it's token based, but I'm confident your team has the skill to resolve it. Thanks!

**Comment by bgt400** [comment] 2024-12-21 14:49
![IMG_1917](https://github.com/user-attachments/assets/acae8166-c98c-41f5-870d-d7229a7ed81f)
![IMG_7816](https://github.com/user-attachments/assets/3c3717af-90fe-41f6-9f1f-b51d19aa5974)

Hello Bolt-Team. It seems the issues are menaining. Bolt works great but that gets really out of controll. Every promt have now a whole list of DO NOT commands.

Looking forward :)

**Comment by gergesh** [comment] 2025-01-06 19:17
Still happening for me as well

**Comment by Aliastom** [comment] 2025-01-07 20:48
Same, it's unbearable

**Comment by RandomlyZay** [comment] 2025-01-08 03:24
Same. And every time, it happens write before I get rate limited, so I have to wait a day to fix what it broke. I'll definitely be telling it to send the full code and restore the placeholders from now on.

**Comment by mangetout89** [comment] 2025-01-11 08:43
> Hi! 👋 Thanks for the comments!
> 
> This is an annoying and recurring. We have ideas on how to reduce it from happening but it's going to take some time.
> 
> For now, there is a workaround: To prevent it from deleting old code, asking it to always provide the full code helps a bit and asking it to restore the placeholders with actual code helps too.

hello, 
can you give us an example how to

**Comment by AntoineGM** [comment] 2025-01-14 07:49
Hi there, 
The issue is not solved at all and it is quite anoying. 

> **🎉 FIX LANDED** we have shipped an update that should permanently resolve this issue! Please share examples if you are still experiencing this error after 1pm PST on October 22'nd.

Should be reopen. 

<img width="305" alt="image" src="https://github.com/user-attachments/assets/ea470138-833a-47ac-94b4-ed06355c4fb7" />

**Comment by jumppard-lfc** [comment] 2025-01-15 11:43
This is still an issue for me as well. 

I kindly asked bolt.new to add additional feature.. in the end of the prompt, I also added this: 

"Please leave all other functionality untouched. Thanks"

The result: bolt.new added the new feature, which is great. But it also removed the code which should stay the same and added a comment saying 

**"{/* ... (keep existing JSX) */}"**

------

Here is the whole description of this issue:

I'm developing a nextjs web app using bolt.new

Here is the user journey what was actually working fine:
1. fill the form 
2. click "create" button
3. save record to db

Then, I prompted bol.new to add some additional steps (see 3,4,5 below):
1. fill the form
2. click "create" button 
3. show additional popup 
4. fill the form in the popup 
5. click "save" button
6. save record to db

In the end of my propt I asked bolt.new to not touch any other functionality ("Please leave all other functionality untouched. Thanks") so everything else stays the same.

The result:
bolt.new generated right code (3,4,5 steps in new user journey), which is great. But it also removed the code which should stay the same and added a comment saying 

**"{/* ... (keep existing JSX) */}"**

It just looks like bol.new is confused by my ask to do not touch anything else but the relevant code.

**Comment by carlosazurmendi** [comment] 2025-02-17 19:46
i feel like it would be easy to do, have the app check to see if the AI response contains characters like "//keep previous code same" or whatever the ai would output... which you can train to specifically output something that can be checked. Afterwards if bolt detects that in it's output restore those lines from a previous output so that it doesn't break the code it wrote before... I was having so many issues with this trying to create a simple app.
