### ISSUE TITLE
You have hit the rate limit. You can continue to code for free in the editor.

### ISSUE THREAD

**Issue by shekhatufayl** [stackblitz/bolt.new#287] opened 2024-10-09 08:42 UTC
### Describe the bug

subscribed to pro version, even without using it once it says : You have hit the rate limit. You can continue to code for free in the editor.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-xvmqvh?utm_campaign=stackblitz-on-page&utm_source=web-app&utm_medium=nav-button

### Steps to reproduce

just signed in saw the message

### Expected behavior

no rate limit would be the best or a display

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by margorpaami** [comment] 2024-10-09 08:44
come into the same situation.I don't think I have used 10M tokens, which is the quota of pro subscription.

**Comment by marioverdu** [comment] 2024-10-09 08:54
In the same situation as the buddies. Makes no sense, I can't have spent 1 million tokens on 15 code changes

**Comment by gameloft333** [comment] 2024-10-09 09:20
why it happen? we're premium developers who had 10m tokens, I don't think we reached the max tokens indeed, please fix this issue since it will affect the work we're doing now.

And one more thing, @Team, 

PLEASE BE MORE CAREFUL TO RELEASE ANY NEW FEATURES THAT YOU WANNA IMPROVE WHICH ARE APPROVED IN SANDBOX MODE BEFORE INDEED, TO AVOID AFFECTING THE  USERS EXACTLY. THK YOU.

**Comment by sulco** [comment] 2024-10-09 10:52
Hey, all! We have been working on optimizing the tokens usage and accidentally triggered the limit on the accounts that weren't close to the limit. We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopters and for your patience as we're ironing out the experience on bolt!

**Closed by sulco** 2024-10-09 10:52 UTC

**Comment by marioverdu** [comment] 2024-10-09 15:51
> Hey, all! We have been working on optimizing the tokens usage and accidentally triggered the limit on the accounts that weren't close to the limit. We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopters and for your patience as we're ironing out the experience on bolt!

Solved! Thanks for being so fast. Great product and great team!

**Comment by abdallahpower** [comment] 2024-10-31 15:04
the problem persist

**Comment by juleatkr** [comment] 2024-11-13 08:54
How the tokens are being used is not mentioned anywhere on the site. For even a small change, Bolt rewrites the entire code instead of editing a specific portion. This is why tokens are being consumed so quickly. Bolt needs to support users in this regard.

**Comment by abdallahpower** [comment] 2024-11-17 21:24
Again and again and again

**Comment by franck403** [comment] 2024-11-21 17:36
After days its not reseting

**Comment by alisufiyan12** [comment] 2024-12-04 23:49
having the same issue plus the issue of token consumption is just huge... even if we write a shorted prompt or a longer once its just consuming .1M tokens per prompt like a just consumed around 6M tokens in few minutes... at least the early subscribers should get some response also nowhere on the website its written anything about the token consumption.

**Comment by yog1b3ar** [comment] 2024-12-05 13:57
having the same issue here. I've only used it for 3 days. If this going to be fixed?

**Comment by myndfire** [comment] 2024-12-11 17:30
having the same issue here. I've only used it for 3 days. Is this going to be fixed?
"You have hit the rate limit. You can continue to code for free in the editor."

**Comment by Anonymousinterpares** [comment] 2024-12-21 14:38
I'm a new user. Supposedly there are 2M tokens to be used but after using 200k I have this very same error.
Seeing comments of others, it seems very risky for me to buy for the paid version...

**Comment by vadimstyr** [comment] 2024-12-23 20:25
The limit is per day 200k token, thats poor

**Comment by chrisalat** [comment] 2025-01-03 00:49
+1

**Comment by aaam0mm** [comment] 2025-01-03 11:18
I'm having the same problem here. I've only used it for a day. Will this issue be fixed? "You have hit the rate limit. You can continue to code for free in the editor."

**Comment by Anonymousinterpares** [comment] 2025-01-03 11:25
I suggest moving to bolt.diy, where you can use your own api keys between different models ;)

**Comment by aaam0mm** [comment] 2025-01-03 11:42
> أقترح الانتقال إلى bolt.diy، حيث يمكنك استخدام مفاتيح API الخاصة بك بين النماذج المختلفة ;)



> I suggest moving to bolt.diy, where you can use your own api keys between different models ;)

I subscribed to a paid version, after a day of subscription this problem appeared! Is it possible that after a day 10,000,000 tokens were finished? Or is there a problem?

**Comment by Esatacar** [comment] 2025-01-04 13:42
I have the pro package with enough tokens, but I started receiving the error "You have hit the rate limit. You can continue to code for free in the editor" after using it for 2-3 hours. I contacted support via email, but nothing changed so far.

**Comment by shaysid** [comment] 2025-01-29 01:26
I'm a new user (Jan/2025) . The problem described above by all still persist and hasn't been resolved. I've also tried opening a new project but face the same issue. This is unacceptable for any paid version. 
I consider requesting a refund and cancel if this error isn't fixed asap. Its damaging, holding me back and I cant make the timelines I've committed on. Any stackblitz member online please respond ASAP with a practical solution.

**Comment by sburakc** [comment] 2025-01-29 06:10
This morning I started my first chat with a new Fork and the error I got in my first message for my Pro account:
You have hit the rate limit. You can continue to code for free in the editor.

**Comment by datboip** [comment] 2025-02-06 06:14
similar issue, bought 10 million tokens, used 2, and already hit the limit? kinda useless.

**Comment by Sandevall-Ghub** [comment] 2025-02-09 02:19
Still an issue it seems are they still working on this project or is this as intended?

**Comment by gabrielengel** [comment] 2025-02-09 19:48
I have just ran into this issue

**Comment by sburakc** [comment] 2025-02-09 20:10
Bolt New AI offers 10 million tokens for $20 with a paid subscription, but they were quickly consumed step by step while adding a JSON file to the left menu. Instead, it would be fairer to count usage based on Agent rights, similar to Replit and Cursor.

For example, Replit offers 100 Agent and 500 chat usage rights for $25 per month, but with an annual plan (using the NEW25 code), the cost effectively drops to $12.5 per month. This means users paying monthly can add another $12.5 in the same month to reach the usual $25 total, gaining an additional 50 Agent and 250 chat rights. This allows them to complete the month with 150 Agent and 750 chat rights for $25, making the system much more flexible. Similarly, Cursor provides 500 fast requests, and even after they run out, users can continue at a slower rate.

However, limiting usage purely by tokens, without controlling how inefficiently the AI might consume them, is not a fair approach. A more balanced system would be to base it on completed agent tasks rather than raw token consumption.

**Comment by gabrielengel** [comment] 2025-02-09 20:39
In my case, I suspect I was working too fast and got Rate Limited by a rack protection. Just wondering when the limit will be available again.

<img width="504" alt="Image" src="https://github.com/user-attachments/assets/81240bf7-1b6f-42ea-ba67-4cb9dc59c9b7" />

**Comment by Stanislao84** [comment] 2025-02-21 15:24
Da oggi faccio parte anch'io del Club degli pseudo divoratori di milioni di token in 3 giorni 🤦‍♂️

**Comment by danlam21** [comment] 2025-02-25 16:52
@sulco when does the rate limit reset? Every 24 hours or?

**Comment by nanodeverlop** [comment] 2025-03-06 02:47
tengo el mismo problema con eso y lo contrate hace 3 dias .

You have hit the rate limit. You can continue to code for free in the editor.

**Comment by masterbinoy** [comment] 2025-03-06 19:18
I am facing the same issue... Please help it has been days now

**Comment by juan90ch** [comment] 2025-03-06 19:20
> I am facing the same issue... Please help it has been days now

i just purchased the pro subscription about 4 hours ago, and no i cannot continue to use it.

**Comment by Drfizzgig** [comment] 2025-03-11 00:45
This is annoying. Ive continued to upgrade because i keep getting credits used msg. There is no way Ive used 26M tokens support isn't helpful. There isn't really clear terminology on the credit system and once you run out are told  "
You have hit the rate limit. You can continue to code for free in the editor."  where the hell is the free editor? And if i can use the free editor what should I have been using my credits for? its a really crap system especially when youre trying to initially build an app.

**Comment by antamb** [comment] 2025-03-13 01:12
same issue here with a pro subscription...

**Comment by Drfizzgig** [comment] 2025-03-13 01:18
> same issue here with a pro subscription...

Great app, buggy and a bummer. Has customer support been able to help?

**Comment by tomwoods** [comment] 2025-03-13 20:03
Prompts me to upgrade to get more credits, shows me on the next page that I still have 900k of the 1M.
![Image](https://github.com/user-attachments/assets/8172ef48-b46d-42d3-b192-b3c5bd7fecd8)
![Image](https://github.com/user-attachments/assets/c7652635-2312-4a4a-b68d-ecac293d7cd4)

**Comment by franck403** [comment] 2025-03-13 20:10
The rate limit seem to be the same for everyone and not checking the account and token left before limiting I think.

**Comment by Drfizzgig** [comment] 2025-03-13 23:08
The best part about this is that customer services just disappeared. I was told someone would reach out and its been a week. Two other agents just flat ignored me. Im hoping its just because they are over whelmed but so far this experience is frustrating What gives SUPABOLT!?

**Comment by zuoxue** [comment] 2025-03-21 08:41
the rule is weired,i can't completely understand it,i had encountered the issue after created two pages,meaningwhile,this is my first sign up and use i.The officier website show us that we can free use it as individual developer

**Comment by Sopka0111** [comment] 2025-03-26 02:17
> Hey, all! We have been working on optimizing the tokens usage and accidentally triggered the limit on the accounts that weren't close to the limit. We've reverted the change so this should now be resolved and you should have **your correct limit back**. I'll close the issue, but in case a problem persist, please open a new one! Thank you for being an early adopters and for your patience as we're ironing out the experience on bolt!

Really because I pay $200 a month and had to spend $100 on tokens over the past four days and haven't even made much change besides it telling me it fixed something that it didnt.

**Comment by codezilla91** [comment] 2025-03-31 09:02
Any solution or workaround to this? 31 March 2025 and i am still getting the same message, even days of not using bolt or generating a single line of code

**Comment by franck403** [comment] 2025-03-31 15:01
Next person with a issue should create a new one

**Comment by alexhuls** [comment] 2025-03-31 22:29
I have the same problem. What can I do?

**Comment by franck403** [comment] 2025-04-01 12:05
Create a new issue

**Comment by Ireheart** [comment] 2025-04-03 10:17
Light use, rate limited but on pro 25. Damn...

**Comment by franck403** [comment] 2025-04-03 14:43
WHO is going to create a NEW issue

**Comment by foxapp** [comment] 2025-04-23 13:56
use for some days but I saw that every day give the same error so unsubscribe and need to find out how to remove my profile from them

**Comment by mahmudhasans** [comment] 2025-05-21 14:24
you have hit the rate limit. you can continue to code for free in the editor.

This is actually unacceptable in any way. Even after not doing any significant work, the limit is being exceeded and the tasks are being stopped with a message. We want a solution to this and if there is a problem in the system, the system should definitely take the driver. For example, when using free tokens, it shows how much news there is, but there is no such option in the case of premium subscription. This is really sad and this can happen to premium users. I hope this problem is resolved.

**Comment by lroy-stack** [comment] 2025-06-18 19:50
Getting the same error in middle of production! Little sucks, just paid 10M tokens and dont seem to be used:


Error
You have hit the rate limit. You can continue to code for free in the editor.

Pls help me to fix it or understand it.
