### ISSUE TITLE
UNUSABLE: This message didn't complete its response.

### ISSUE THREAD

**Issue by paulgosnell** [stackblitz/bolt.new#936] opened 2024-10-25 15:32 UTC
### Describe the bug

can't even send a single message now without seeing this error message!

### Link to the Bolt URL that caused the error

https://bolt.new/~/chilledcrm-puskmq

### Steps to reproduce

Send a message

### Expected behavior

To be able to complete a task

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 108392343,
  "usedJSHeapSize": 87056559,
  "jsHeapSizeLimit": 2172649472
}
Username = paulgosnell
Chat ID = a29fab355a92
```

**Comment by kc0tlh** [comment] 2024-10-29 20:18
Closing as duplicate of #1073

**Closed by kc0tlh** 2024-10-29 20:18 UTC
