### ISSUE TITLE
Bug: Project Not Persisted To Backend for Some Free Tier Users (RESOLVED)

### ISSUE THREAD

**Issue by tincleo** [stackblitz/bolt.new#50] opened 2024-10-05 12:02 UTC
### Describe the bug

Project suddenly disappeared after page refresh, making me to lose 4 hours of work in an instant. :-/

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-vanilla-vite-6e7ljo

### Steps to reproduce

Browser window got refreshed and the project disappeared completely.

### Expected behavior

Browser window got refreshed and the project had disappeared.

### Screen Recording / Screenshot

![Screenshot 2024-10-05 at 12 56 59](https://github.com/user-attachments/assets/a6f8180c-869b-46ec-a6aa-46947b128926)

### Platform

```
Browser name = Chrome
Full version = 129.0.0.0
Major version = 129
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82182935,
  "usedJSHeapSize": 80779135,
  "jsHeapSizeLimit": 2172649472
}
Username = tincleo
Chat ID = eb14bf1cab7d
```

### Additional context

Please add some versioning to save versions while building something.

**Comment by kc0tlh** [comment] 2024-10-16 22:49
Apologies for this frustrating experience!

While there is a bug affecting a small number of free users (see below for more info) it is possible that what you are experiencing is simply related to our current limited chat persistence model. Chat history is currently not persisted across browsers/devices, and chats will disappear from the Bolt.new UI if your cache is cleared, so it is possible that your project was actually saved to StackBlitz behind the scenes. If that is the case, you can find your project on [StackBlitz.com](http://stackblitz.com/) (same account as Bolt.new) > Collections Tab > Bolt collection. If this is you, we are landing improved chat persistence in 1-2 weeks and you can track that in issue 39.

Unfortunately, If your project is not stored there, then it is likely you are experiencing the bug described below:
Our engineering team has been looking at the logs and links that were provided related to this issue (thanks for providing these) and we have identified a root cause affecting a small number of users on our free tier rate limits. We are shipping a fix now but unfortunately are unlikely to be able to recover projects that ran into this error. We are working as I type this to ship the fix!

While bugs can happen during beta periods, we are sorry that you experienced this! I want to thank everyone that reported this issue and provided project links and information as it was key in identifying and resolving this issue for everyone going forward :man-bowing:

**Comment by kc0tlh** [comment] 2024-10-22 20:44
**🎉 This fix has been shipped to production:** This should not affect any users going forward!

If you are looking for a missing project, here's where you should find it:

**Find Missing Chats or Open Chats On a New Browser/Device** 
1. Login to StackBlitz.com (same account as Bolt.new) 
2. Open the Collections Tab
3. Open the Bolt collection
4. Open the project you want to edit in Bolt
5. Press the "Open in Bolt" button and continue coding!

**Closed by kc0tlh** 2024-10-22 20:44 UTC
Labels: tracked

**Comment by Jedimind369** [comment] 2024-10-24 12:54
Dear Bolt.new Support Team,

I am writing to follow up on my previous communication regarding the loss of my project, "Advanced Bookmark Management System with React and TypeScript." I appreciate the recent update indicating that a fix has been shipped to production, but unfortunately, this does not resolve my specific issue.

To reiterate my situation:

- **Paid User Status**: I was using a paid plan when my project disappeared. This incident has significantly impacted my work, and I believe it warrants additional attention beyond what has been provided for free-tier users.
  
- **Project Recovery Attempts**: I have followed the suggested steps to locate missing projects via StackBlitz.com under the Collections Tab > Bolt collection. However, my original project is not there. The files currently available were created after the loss as I attempted to restart my work.

Given these circumstances, I am requesting:

1. **A thorough investigation** into what happened to my original project and any potential recovery options available for paid users.
   
2. **A refund or token reset** due to the disruption caused by this data loss, reflecting my status as a paying customer.

I understand that bugs can occur during beta periods, but as a paying user, I expected a higher level of data protection and customer support. Could you please escalate this issue to ensure it receives the necessary attention?

Thank you for your assistance. I look forward to your response and a satisfactory resolution to this matter.

Best regards,
Alex

**Comment by kc0tlh** [comment] 2024-10-29 18:28
@Jedimind369 absolutely! Please reach out to hello@stackblitz.com with the same info as above + project URLs for assistance with this!

**Comment by danishmbutt** [comment] 2024-11-11 18:56
while you are fixing the bug for chat persistence -- what is the guidance to store the chat-projects? can i save it locally or in github? its not clear how bolt.new projects can be saved.

**Comment by LukaBanovic** [comment] 2025-03-03 07:52
I'm a paid user as well and have the same experience. My project is stored on Stackblitz, however the import to bolt doesn't work correctly, still get a "Failed to load your chats" error. 

This issue does not effect only free users. I've spent quite some time convincing our company to pay for a subscription package, built several projects with it, so I'll give it a few days before I go there and convince them to switch to Lovable. 

This bug is absolutely critical causing not only an unacceptable time loss but also a huge level of risk for the future. 

@kc0tlh Any news on when we are to expect a fix?
