### ISSUE TITLE
Can't send message on cloned repo

### ISSUE THREAD

**Issue by nalaso** [stackblitz/bolt.new#86] opened 2024-10-06 08:58 UTC
### Describe the bug

I followed the steps from contributions.md

1. pnpm install
2. Added the environment variables.
3. pnpm run dev.

However, for some reason even when I press enter, nothing happens. I tried adding console.log statements in the code, but they aren't working either.

### Link to the Bolt URL that caused the error

-

### Steps to reproduce

1. pnpm install
2. Added the environment variables.
3. pnpm run dev.

### Expected behavior

App should start creating project.

### Screen Recording / Screenshot

<img width="904" alt="image" src="https://github.com/user-attachments/assets/d341f564-ae70-4a94-810e-809bf82f9d76">
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/2834b241-ad18-41a5-ab48-f6f87f0dd7e3">

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [latest]

**Comment by samdenty** [comment] 2024-10-06 17:34
👋 I've ran into this as well locally, and during testing had to use Chrome canary to test bolt.

The root cause is https://github.com/vitejs/vite/issues/18156, caused by a regression in chrome 129. It was fixed in chrome 130.

I'll see if we can commit a workaround on monday

**Comment by VersaceXcodes** [comment] 2024-10-06 19:57
> 👋 I've ran into this as well locally, and during testing had to use Chrome canary to test bolt.
> 
> The root cause is [vitejs/vite#18156](https://github.com/vitejs/vite/issues/18156), caused by a regression in chrome 129. It was fixed in chrome 130, but that's only in canary at the minute and the fix hasn't been backported. Can you confirm you're on chrome 129 in `chrome://version`?
> 
> I'll see if we can commit a workaround on monday

@samdenty Another issue, the progress of each step is not shown till after all steps are completed

**Comment by nalaso** [comment] 2024-10-07 02:32
> chrome://version

129.0.6668.90 (Official Build) (arm64)

**Comment by LIdro** [comment] 2024-10-07 04:39
Yep. Browser problem. It works well with firefox.

**Comment by samdenty** [comment] 2024-10-07 17:53
in https://github.com/stackblitz/bolt.new/pull/157 i added a screen showing the an error message instead of the app just not working. I'll close this issue, but i've linked to it on that screen

**Closed by samdenty** 2024-10-07 17:53 UTC
Labels: tracked

**Comment by Analyst1981** [comment] 2024-10-10 04:15
Please use Chrome Canary for testing.
Chrome 129 has an issue with JavaScript modules & Vite local development, see [for more information.](https://github.com/stackblitz/bolt.new/issues/86#issuecomment-2395519258)

Note: This only impacts local development. `pnpm run build` and `pnpm run start` will work fine in this browser.

**Comment by saurav-shakya** [comment] 2024-10-13 09:09
![image](https://github.com/user-attachments/assets/d4661f6b-07fe-47d2-b25e-6a813677ea2f)
this is prolem show, plz provide solution.

**Comment by khalidmaquilang** [comment] 2024-10-17 11:37
i had this issue but upgrading my chrome to 130.. fixed it
