### ISSUE TITLE
It looks like we're having trouble connecting due to the location of the server you're connected to- if this is in error, can you try switching your VPN location?

### ISSUE THREAD

**Issue by domspantaleon** [stackblitz/bolt.new#77] opened 2024-10-06 02:01 UTC
### Describe the bug

I recently found out about you guys and wanted to play with it. However, I cant seem to make it work. Whatever prompt I type it keeps giving me forbidden error. I even subscribed to PRO just to make sure I have not reach the free tier limit but I got the same forbidden error. I also tried very simple prompt like this
"a simple landing page website for my pottery business", still I get forbidden.
I also tried using a different browser (chrome and safari) but still the same error.

<img width="490" alt="image" src="https://github.com/user-attachments/assets/b9547f74-eaaa-4c89-a0be-0a56ab5fd3c8">

### Link to the Bolt URL that caused the error

i dont have a link as I was not able to generate anything

### Steps to reproduce

1. Login
2. Type a prompt
3. click submit button

### Expected behavior

to give result to my prompt

### Screen Recording / Screenshot

https://github.com/user-attachments/assets/a9e7fe4b-079b-437b-ad9e-4d2f13009125

### Platform

- OS: macOS
- Browser: Chrome and Safari
- Version: Chrome -129.0.6668.90 , Safari-18.0.1 (20619.1.26.31.7)

### Additional context

my user name is dombi

**Comment by bsour** [comment] 2024-10-06 05:09
having the same issue

**Comment by benjamin-jun-li** [comment] 2024-10-06 06:29
Same issue, it didn't even work for the first time

**Comment by homeward99** [comment] 2024-10-06 07:14
same here

**Comment by ac1982** [comment] 2024-10-06 12:52
Same here

**Comment by resetsix** [comment] 2024-10-06 16:43
After my personal test, Japan, Singapore, Taiwan, and mainland China can use it normally, but Hong Kong will also have the same ban problem.

So you can try to switch IP

**Comment by brovio** [comment] 2024-10-07 04:06
Vietnam says no...

**Comment by resetsix** [comment] 2024-10-07 07:01
@bsour @SassDude Try using a different IP address from another country or region. Forbidden may be due to regional restrictions.

**Comment by benjamin-jun-li** [comment] 2024-10-07 07:08
Apparently not working for Australia...

**Comment by resetsix** [comment] 2024-10-07 07:10
> Apparently not working for Australia...

Asia may be able to

**Comment by bsour** [comment] 2024-10-07 07:11
It worked for me this morning (Australia)

**Comment by Wangxs404** [comment] 2024-10-07 07:21
solved the problem using my phone's hotspot, and the home Wi-Fi always reported errors (China)

**Comment by resetsix** [comment] 2024-10-07 07:24
> solved the problem using my phone's hotspot, and the home Wi-Fi always reported errors (China)

This should be the operator's problem. There's nothing you can do about it. This is just how China is.

**Comment by Wangxs404** [comment] 2024-10-07 07:38
solved the problem using my phone's hotspot, and the home Wi-Fi always reported errors (China)

**Comment by lazuee** [comment] 2024-10-08 02:28
This only works on selected countries which is I'm sad to know about.
Use VPN > netherlands, to make it work.

**Comment by keithhegit** [comment] 2024-10-08 03:43
same issue (HK)

**Comment by resetsix** [comment] 2024-10-08 11:02
@Nemikolh  Hello, and thank you for your contribution to this project. The “Forbidden” issue seems to be quite serious, as it involves a wide range of regions and may occur regardless of whether the user has a Pro subscription. Does the official website also not know the cause of this problem?

Initially:
- Japan, Singapore, Taiwan and mainland China: access is normal
- Hong Kong: “Access Forbidden” error

Current situation:
- All the above regions now have “Access Forbidden” errors
- Only the United States, Russia and Canada can access normally

I would like to know if the team knows the root cause of this issue. We would appreciate it if you could provide any insights or updates.

Thank you for taking the time to look into this matter.

**Comment by Aeon-Avinash** [comment] 2024-10-08 12:50
Seems Bolt.new is FORBIDDEN in India too!
I've been getting the same "Forbidden" error from for the last six hours or so and it didn't occur to me that it could be because of some geo location error. With an US IP from a VPN, I didn't face any such issue. 
Hope you guys fix this rather unusual glitch.

**Comment by exceedsystem** [comment] 2024-10-08 14:35
The same issue is still occurring in Japan as well. Are shared IP addresses provided by Internet Service Providers (ISPs) causing the problem?

**Comment by santosh610610** [comment] 2024-10-08 15:21
trying for 1st time, India, encountering this issue of "Forbidden" - hope it is being worked on. Thanks! Looks promising!

**Comment by jirojirocirociro** [comment] 2024-10-08 15:26
maybe it is an ai token issue.

**Comment by samdenty** [comment] 2024-10-08 16:37
we've just updated the message to read:

> Our upstream AI provider blocks usage in your IP's country. Please try changing your VPN location.

**Comment by kirjavascript** [comment] 2024-10-09 12:20
Hi all!

We have deployed what we believe may be a fix for this issue.

Could you try accessing again to see if the problem is resolved for you, and let us know the result?

**Comment by resetsix** [comment] 2024-10-09 12:31
> Hi all!
> 
> We have deployed what we believe may be a fix for this issue.
> 
> Could you try accessing again to see if the problem is resolved for you, and let us know the result?

Thank you for all your hard work, and it seems that everything has returned to normal.

**Comment by domspantaleon** [comment] 2024-10-10 00:41
Still a problem here in the Philippines. Still haven't used this product since I upgraded to pro...
I don't intend to spend extra money on VPN just to try this product.
![image](https://github.com/user-attachments/assets/c30702ae-e482-4a44-9c10-4073480c1fd6)

**Comment by jamesofficer** [comment] 2024-10-10 09:43
Getting this issue in Australia (not connected to a VPN).

**Comment by snowdream** [comment] 2024-10-10 10:59
same issue

**Comment by benjamin-jun-li** [comment] 2024-10-10 11:07
same issue in Australia

**Comment by samdenty** [comment] 2024-10-11 06:50
It looks like we didn't actually fully resolve this issue

**Comment by samdenty** [comment] 2024-10-11 13:23
we've just shipped a fix, please confirm it now works!

**Closed by samdenty** 2024-10-11 13:23 UTC
Labels: tracked

**Comment by lazuee** [comment] 2024-10-11 14:54
Thanks for the update! I can confirm that the issue has been resolved and it's working as expected here in the Philippines.

**Comment by Towoadeyemi1** [comment] 2024-10-17 01:31
Same server error in Alberta, Canada. It's been doing this for at least 2 days. 
![Screenshot 2024-10-16 193009](https://github.com/user-attachments/assets/ab914cf0-907f-45ff-80e9-05e479e29713)

**Comment by samdenty** [comment] 2024-10-17 01:35
@Towoadeyemi1 can you open a separate issue?

**Comment by Towoadeyemi1** [comment] 2024-10-17 01:48
I have opened a separate issue.

Thanks

**Comment by Towoadeyemi1** [comment] 2024-10-17 02:22
Are you attending to it?

**Comment by Towoadeyemi1** [comment] 2024-10-24 12:36
Please I’ll want my tokens or money refunded as I got absolutely no value. Errors that didn’t make sense until all my tokens were used up.Thanks Sent from my iPhoneOn 16 Oct 2024, at 20:22, Towo Adeyemi ***@***.***> wrote:﻿Are you attending to it?On Wed, Oct 16, 2024 at 7:48 PM Towo Adeyemi ***@***.***> wrote:I have opened a separate issue.ThanksOn Wed, Oct 16, 2024 at 7:36 PM Sam Denty ***@***.***> wrote:
@Towoadeyemi1 can you open a separate issue?
