### ISSUE TITLE
failed to save project message.

### ISSUE THREAD

**Issue by Glordbzh** [stackblitz/bolt.new#3558] opened 2024-12-02 16:31 UTC
### Describe the bug

I get the message "failes to save project" all the time. 

I waste my tokens all the time and I've been starting from scratch for several days. 
Can you please help me to fix this?

Thank you in advance.

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-aqzpn9

### Steps to reproduce

When I want to save and deploy my project on Netlify the message appears. When I open my project, I have lost all my progress.

### Expected behavior

help me plz to solve this probleme and give me back my tokens plz.

### Screen Recording / Screenshot

![Image 12-2-24 at 5 30 PM](https://github.com/user-attachments/assets/403e3543-c298-4d21-bc81-52139b7c006d)

### Platform

macos
chrome

**Comment by endocytosis** [comment] 2024-12-02 16:38
Appreciate the feedback! We are tracking this issue [here](https://github.com/stackblitz/bolt.new/issues/2762). Could you open browser DevTools, go to the Network panel, and look for an erroneous request (it will be in red) if you encounter this again?

![image](https://github.com/user-attachments/assets/502893e9-194e-45b1-a427-7d311d8d40f9)

This will help us determine the cause of this issue. Thanks!

**Comment by Glordbzh** [comment] 2024-12-02 17:16
Thank you for your help and sorry my english is so bad (I am French )


Here is a screenshot of the devtools network panel.

Thank you for your help.

Gaylord Beauchamp.

**Comment by Glordbzh** [comment] 2024-12-02 17:17
![Uploading Image 12-2-24 at 6.13 PM.jpeg…]()

**Comment by Glordbzh** [comment] 2024-12-02 17:25
![Image 12-2-24 at 6 13 PM](https://github.com/user-attachments/assets/c92e0775-4494-43da-9b94-125e0d8ae0b3)

here is the screenshot

**Comment by endocytosis** [comment] 2024-12-02 18:03
Hi @Glordbzh, 

Really appreciate the feedback as this will help the team get to the root causes of the issue! We will continue to track this [here](https://github.com/stackblitz/bolt.new/issues/2762).

**Closed by endocytosis** 2024-12-02 18:03 UTC

**Comment by Glordbzh** [comment] 2024-12-02 18:09
Can you give me some of my tokens back because I spend a lot for nothing.

Thank you
