### ISSUE TITLE
Lost the conversation history after upgrading

### ISSUE THREAD

**Issue by rafapple** [stackblitz/bolt.new#601] opened 2024-10-15 14:49 UTC
### Describe the bug

I was well on my way to the final result I expected of the app I was generating, but then it crashed. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/sb1-uhthnw

### Steps to reproduce

As I was running out of free tokens, I made the purchase of the pro plan, and when I came back I lost all my project files, my progress.... I don't have access to the previous versions of the app. This is very sad, I'll have to do it all over again, and I really liked where I was headed. When I reloaded the conversation from the previous chats, the chat log was gone. Some project files were present, but completely different from the ones I had before. Totally unrelated.

### Expected behavior

I expect to keep the history of everything I do in bolt, and be able to roll back in case something goes sideways.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

I'm a new user.

**Comment by kc0tlh** [comment] 2024-10-22 18:20
Apologies for this frustrating experience!

While there is a bug affecting a small number of free users (see below for more info) it is possible that what you are experiencing is simply related to our current limited chat persistence model. Chat history is currently not persisted across browsers/devices, and chats will disappear from the Bolt.new UI if your cache is cleared, so it is possible that your project was actually saved to StackBlitz behind the scenes. If that is the case, you can find your project on [StackBlitz.com](http://stackblitz.com/) (same account as Bolt.new) > Collections Tab > Bolt collection. If this is you, we are landing improved chat persistence in 1-2 weeks and you can track that in issue 39.

Unfortunately, If your project is not stored there, then it is likely you are experiencing the bug described below:
Our engineering team has been looking at the logs and links that were provided related to this issue (thanks for providing these) and we have identified a root cause affecting a small number of users on our free tier rate limits. We are shipping a fix now (updates on that to come in the main issue #50) but unfortunately are unlikely to be able to recover projects that ran into this error. 

While bugs can happen during beta periods, we are sorry that you experienced this! I want to thank everyone that reported this issue and provided project links and information as it was key in identifying and resolving this issue for everyone going forward 🙇

**Closed by kc0tlh** 2024-10-22 18:20 UTC

**Comment by dustinw22** [comment] 2024-11-12 00:43
definitely still an issue

**Comment by Ezyrex** [comment] 2024-11-21 17:15
I'm a paid member and have been facing the same frustrating issue for the past three days. If I refresh the browser or leave the screen for a while, I lose all the progress I’ve made, including my most recent chat history. All the back-and-forth communication disappears, along with the features I implemented. This has caused me to lose millions of tokens by repeatedly implementing the same features.
Although I download my code and save it in StackBlitz, it doesn't protect me from losing the most recent chats.
What steps can I take to ensure my progress and chat history are preserved, even if I refresh the browser or leave the screen?
I sent couple of emails but there is no reply yet !

**Comment by Worthiit** [comment] 2025-02-07 20:10
I'm also a paid user and have been facing the similar issue like i can't revert back to old chats cuz they are really gone.

**Comment by 0xodd** [comment] 2025-02-16 13:24
I'm having that same issue its very frustrating to waste tokens on errors then for that chat to poof so I can't roll back it's a joke

**Comment by Worthiit** [comment] 2025-02-16 13:37
I contacted the bolt customer service, they were fast enough to respond but it was no help , not at all , they said they are working on this problem and will update me soon when it's fixed. At this rate try moving to lovable, it gives 5 messages per for free so go and give it a try.
