### ISSUE TITLE
Preview not visible 

### ISSUE THREAD

**Issue by lubosi** [stackblitz/bolt.new#3806] opened 2024-12-06 21:53 UTC
### Describe the bug

The preview not working - the preview is just blank. 

### Link to the Bolt URL that caused the error

https://bolt.new/~/bolt-slidev-fnpsf9

### Steps to reproduce

tried even to use basic Bolt pre-defined prompts. 

### Expected behavior

The preview should show the UI of the code. 

### Platform

```
Browser name = Chrome
Full version = 131.0.0.0
Major version = 131
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 346766794,
  "usedJSHeapSize": 339130766,
  "jsHeapSizeLimit": 4294705152
}
Username = lubosi
Chat ID = 8175ba8e2ef6
```

### Additional context

Tried to debug it with prompts but still errors

**Comment by AriPerkkio** [comment] 2024-12-07 08:56
Duplicate of https://github.com/stackblitz/bolt.new/issues/3807

**Closed by AriPerkkio** 2024-12-07 08:56 UTC
